addon-mirage-support/factories/case.js
addon-mirage-support/factories/work-item.js
addon/mirage-graphql/handler.js
addon/mirage-graphql/mocks/base.js
addon/mirage-graphql/schema.graphql
package.json
tests/unit/mirage/mocks/work-item-test.js
yarn.lock

... and also update the schema.

Add missing properties to case and workflow factory, add test

---

addon/components/cfb-form-editor/question.js
addon/components/cfb-form-list.js
addon/routes/edit/questions/edit.js
addon/templates/components/cfb-form-editor/question.hbs
addon/templates/edit/questions/edit.hbs
addon/validations/question.js
tests/acceptance/navigation-test.js
tests/integration/components/cfb-form-editor/question-test.js
translations/en-us.yaml

This should improve UX on the "FormQuestion" form. I also made the submit button on each form enabled, even when the form is invalid for better UX.

Formbuilder: Use dropdown for row form instead of text field

---

addon/components/cfb-form-editor/question-list/item.js
addon/gql/mutations/add-form-question.graphql
addon/gql/mutations/remove-form-question.graphql
addon/gql/mutations/reorder-form-questions.graphql
addon/gql/queries/search-form-question.graphql
addon/templates/components/cfb-form-editor/question-list/item.hbs
app/styles/cfb-form-editor/question-list/_item.scss

This only applies to the list of questions already assigned to a form.
We still don't show - and don't intend to - archived questions when adding new questions.

Change question list to show archived

---

addon/components/cf-field/input/float.js
addon/components/cf-field/input/integer.js

Just checking for falsy falsely classifies zero.
I might be wrong. But - IMO - zero is a valid integer and float.
Resolves #61

ADD isNaN check to allow for zero

---

addon/components/cfb-form-editor/question.js
addon/templates/components/cfb-form-editor/question.hbs
translations/de-de.yaml
translations/en-us.yaml

Add hidden field in "advanced settings" block

---

addon/-private/fragment-types.js
addon/components/cf-field-value.js
addon/components/cf-field/input/table.js
addon/components/cfb-form-editor/question.js
addon/gql/mutations/save-form-question.graphql
addon/gql/queries/form-editor-question.graphql
addon/mirage-graphql/mocks/question.js
addon/mirage-graphql/schema.graphql
addon/templates/components/cf-field-value.hbs
addon/templates/components/cf-field/input/table.hbs
addon/templates/components/cfb-form-editor/question.hbs
addon/validations/question.js
app/components/cf-field-value.js
tests/integration/components/cf-field-value-test.js
tests/integration/components/cf-field/input/table-test.js
tests/integration/components/cfb-form-editor/question-test.js
translations/de-de.yaml
translations/en-us.yaml

This is based on #69, please merge that one first.

 Table question: Add rows to table after first submit

---

addon/components/cf-form.js
addon/templates/components/cf-field.hbs
addon/templates/components/cf-form.hbs

* Specify overriding components via slug.
* Reference other questions via slug.

ADD component overrides and crossreferences

---

renovate.json

Got this from
https://github.com/ember-decorators/ember-decorators/blob/master/renovate.json

Renovate: Group ember infra packages

---

.travis.yml
addon/components/cf-form.js
tests/dummy/app/components/override.js
tests/integration/components/cf-form-test.js

Resolves #73 
Not sure if the component at `tests/dummy/app/components/override.js` is a good idea.

ADD widget override documentation and test

---

addon/components/cf-field.js
addon/components/cf-field/errors.js
addon/components/cf-field/input/text.js
addon/components/cf-navigation.js
addon/gql/fragments/form-document.graphql
addon/gql/queries/get-document.graphql
addon/gql/queries/get-navigation.graphql
addon/lib/document.js
addon/lib/field.js
addon/lib/question.js
addon/templates/components/cf-field.hbs
addon/templates/components/cf-navigation.hbs
app/components/cf-navigation.js
tests/dummy/app/router.js
tests/dummy/app/routes/nested.js
tests/dummy/app/routes/nested/detail.js
tests/dummy/app/styles/app.scss
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/nested.hbs
tests/dummy/app/templates/nested/detail.hbs
tests/integration/components/cf-field-test.js
tests/integration/components/cf-field/input/text-test.js
tests/integration/components/cf-navigation-test.js
translations/de-de.yaml
translations/en-us.yaml

Depends on https://github.com/projectcaluma/caluma/pull/349

Subform navigation

---

package.json
yarn.lock

Just until a version with the necessary changes has been released.

UPDATE dependency to upstream master

---

addon/components/cf-field/input.js
addon/components/cfb-form-editor/question.js
addon/templates/components/cfb-form-editor/question.hbs
translations/de-de.yaml
translations/en-us.yaml

widgetType is being replaced by the more generic widgetOverride.

REMOVE widgetType and related code

---

addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/options.js
addon/templates/components/cfb-form-editor/question/options.hbs
addon/validations/option.js
addon/validations/question.js
tests/integration/components/cfb-form-editor/question-test.js

 Increase max length on question and option labels

---

README.md
addon/components/cfb-form-editor/question.js
addon/templates/components/cf-field.hbs
addon/templates/components/cfb-form-editor/question.hbs
tests/integration/components/cf-field-test.js
tests/integration/components/cfb-form-editor/question-test.js
translations/de-de.yaml
translations/en-us.yaml

Add new meta option for Choice question to hide their labels.
Closes #124

Add option to hide label of choice questions

---

addon-mirage-support/factories/answer.js
addon-mirage-support/factories/file.js
addon-mirage-support/factories/question.js
addon/components/cf-field/input/file.js
addon/components/cfb-form-editor/question.js
addon/gql/fragments/field-answer.graphql
addon/gql/mutations/save-document-file-answer.graphql
addon/gql/mutations/save-file-question.graphql
addon/gql/queries/get-fileanswer-info.graphql
addon/lib/answer.js
addon/lib/field.js
addon/mirage-graphql/handler.js
addon/mirage-graphql/mocks/answer.js
addon/mirage-graphql/mocks/question.js
addon/templates/components/cf-field/input/file.hbs
app/components/cf-field/input/file.js
docker-compose.yml
tests/dummy/mirage/config.js
tests/integration/components/cf-field/input/file-test.js
tests/integration/components/cf-form-test.js
tests/integration/components/cfb-form-editor/question-test.js
translations/de-de.yaml
translations/en-us.yaml

There are some things missing:

WIP: Add file questions

---

addon/components/cf-field/input/file.js

Corrupt URI from error-testing... :see_no_evil:

FIX regression from testing

---

addon-mirage-support/factories/question.js
addon/-private/fragment-types.js
addon/components/cf-field/input/static.js
addon/components/cfb-form-editor/question.js
addon/gql/fragments/field-question.graphql
addon/gql/mutations/save-static-question.graphql
addon/gql/queries/form-editor-question.graphql
addon/lib/field.js
addon/mirage-graphql/mocks/question.js
addon/mirage-graphql/schema.graphql
addon/templates/components/cf-field.hbs
addon/templates/components/cf-field/input/static.hbs
addon/templates/components/cfb-form-editor/question.hbs
app/components/cf-field/input/static.js
tests/integration/components/cfb-form-editor/question-test.js
translations/de-de.yaml
translations/en-us.yaml

Depends on
https://github.com/projectcaluma/caluma/pull/396
Closes #144

feat(form): add support for static question

---

addon/lib/document.js
tests/unit/lib/document-test.js

https://github.com/projectcaluma/caluma/issues/406

feat(jexl): add "interesects" binary operator

---

addon/components/cf-field/input/file.js
addon/components/cfb-form-editor/question.js
addon/utils/and.js
addon/utils/or.js

* Update doc-comments
* Move function into class (make method)

REFACTOR code to remove build warnings

---

addon/components/cf-navigation-item.js
addon/templates/components/cf-navigation-item.hbs
addon/templates/components/cf-navigation.hbs

Also remove top-level question because it provided no real value and
broke the styling

fix(cf-navigation): auto-link empty form sections to first subsection

---

addon/components/cf-field/input.js
addon/components/cf-field/input/checkbox.js
addon/components/cf-field/input/powerselect.js
addon/components/cf-field/input/radio.js
addon/components/cfb-form-editor/question.js
addon/gql/fragments/field-question.graphql
addon/gql/mutations/save-dynamic-choice-question.graphql
addon/gql/mutations/save-dynamic-multiple-choice-question.graphql
addon/gql/queries/all-data-sources.graphql
addon/gql/queries/data-source.graphql
addon/gql/queries/form-editor-question.graphql
addon/lib/field.js
addon/mirage-graphql/schema.graphql
addon/services/caluma-options.js
addon/templates/components/cf-field/input/checkbox.hbs
addon/templates/components/cf-field/input/powerselect.hbs
addon/templates/components/cf-field/input/radio.hbs
addon/templates/components/cfb-form-editor/question.hbs
tests/integration/components/cf-field/input-test.js
tests/integration/components/cf-field/input/checkbox-test.js
tests/integration/components/cf-field/input/radio-test.js
translations/de-de.yaml
translations/en-us.yaml

Add DynamicChoiceQuestion & DynamicMultipleChoiceQuestion

---

addon/lib/field.js

When the code expects an array (`.map`).

Change some get to getWithDefault

---

package.json
yarn.lock

See also: https://github.com/adfinis-sygroup/semantic-release-config

feat(tooling): add semantic release

---

addon/styles/addon.scss
addon/templates/components/cf-field/input/checkbox.hbs

> Einrückung bei mehrzeiligem Text auf Seite «Bestätigung»

Add alignment for checkbox label text

---

addon/lib/document.js

Not sure if that fixes everything. But it would at least be a start :smile:

fix: consider empty but required fields

---

addon/components/cf-field/input/table.js
addon/lib/field.js

 fix(validation): add validation for static, fix multiple choice

---

addon/templates/components/cf-field/input/table.hbs
package.json
yarn.lock

Table modals should not be closable via backdrop

---

addon/components/cfb-jexl-boolean-toggle-switch.js
addon/templates/components/cfb-form-editor/question.hbs
addon/templates/components/cfb-jexl-boolean-toggle-switch.hbs
addon/templates/components/cfb-toggle-switch.hbs

I couldn't find a Jexl expression that worked. Somehow the transforms weren't loaded in my environment. But the code should be find.

feat: add jexl textarea for isRequired

---

addon/templates/components/cf-field/input/table.hbs

fix(table): disable form in table on disabled question

---

addon-mirage-support/factories/form.js
addon-mirage-support/factories/option.js
addon-mirage-support/factories/question.js
addon/-private/fragment-types.js
addon/mirage-graphql/handler.js
addon/mirage-graphql/resolvers/index.js
addon/mirage-graphql/schema.graphql
tests/integration/components/cfb-form-editor/question-test.js

fix(mirage): update mirage schema and fix generic scalar type

---

addon/components/cfb-form-editor/question.js
tests/integration/components/cfb-form-editor/general-test.js
tests/integration/components/cfb-form-editor/question-test.js

Depends on #263 
CC @Yelinz, I think this was your feature. Please look at the changes I made (8bb90b00ca6ba940b49116662a6f8ae154fe6961) to make this work properly!

 fix(form builder): fix handling of existing metadata

---

addon/components/cfb-form-editor/question.js
addon/mirage-graphql/resolvers/index.js
addon/templates/components/cfb-form-editor/question.hbs
addon/validations/question.js
package.json
tests/integration/components/cfb-form-editor/question-test.js
translations/de-de.yaml
yarn.lock

Depends on #264 
Closes #27 
Closes #28

fix(form builder): fix usage of nested properties in the question editor

---

CHANGELOG.md
package.json

This updates the changelog to match the releases and bumps the package.json to the right version

chore: fix version in package and changelog

---

addon/components/cf-pagination.js
addon/templates/components/cf-content.hbs
addon/templates/components/cf-pagination.hbs
app/components/cf-pagination.js
tests/integration/components/cf-pagination-test.js
translations/de-de.yaml
translations/en-us.yaml

feat(navigation): add previous / next pagination

---

addon/helpers/atob.js
addon/helpers/decode-id.js
addon/lib/document.js
addon/lib/field.js
addon/mirage-graphql/mocks/task.js
addon/services/document-store.js
app/helpers/decode-id.js
tests/dummy/app/routes/index.js
tests/dummy/app/routes/nested.js
tests/integration/helpers/decode-id-test.js

chore(atob): rename atob helper to decodeId

---

addon/components/cf-field/info.js
addon/templates/components/cf-field/info.hbs

fix(form): allow stacking of info modals

---

renovate.json

Depends on https://github.com/projectcaluma/renovate-config/pull/14

chore(renovate): automerge docker digest updates

---

addon/components/cfb-float-input.js
addon/components/cfb-float-input/input.js
addon/templates/components/cfb-form-editor/question.hbs
app/components/cfb-float-input.js
app/components/cfb-float-input/input.js
tests/integration/components/cfb-float-input-test.js
tests/integration/components/cfb-float-input/input-test.js

fix(form builder): fix float inputs

---

index.js

fix(babel): remove obsolete babel config

---

addon/lib/document.js
addon/lib/question.js
tests/unit/lib/document-test.js
tests/unit/lib/question-test.js

feat(form): pass form and root form as context for jexl expressions

---

addon/components/cf-field/input/file.js
addon/components/cf-field/input/float.js
addon/components/cf-field/input/integer.js
addon/components/cf-field/input/text.js
addon/components/cf-field/input/textarea.js
addon/templates/components/cf-field/input/radio.hbs
tests/integration/components/cf-field/input-test.js
tests/integration/components/cf-field/input/file-test.js
tests/integration/components/cf-field/input/float-test.js
tests/integration/components/cf-field/input/integer-test.js
tests/integration/components/cf-field/input/powerselect-test.js
tests/integration/components/cf-field/input/radio-test.js
tests/integration/components/cf-field/input/text-test.js
tests/integration/components/cf-field/input/textarea-test.js
tests/unit/lib/field-test.js

This reverts the changes made in #356 and fixes that issue in another way.

fix(form): fix resetting of values on slow input

---

addon/templates/components/cf-field/label.hbs
package.json
yarn.lock

chore: remove obsolete dependency ember-promise-helpers

---

addon/templates/components/cf-field/info.hbs
tests/dummy/app/templates/index.hbs
yarn.lock

Small change to get the dummy page working again.

fix(dummy): change cf-form to cf-content

---

addon/components/cfb-form-editor/question-list/item.js
addon/lib/field.js
addon/lib/question.js
addon/utils/jexl.js
package.json
tests/unit/lib/field-test.js
tests/unit/utils/jexl-test.js
yarn.lock

This should serve as a reminder that we need to update JEXL as soon as https://github.com/TomFrost/Jexl/pull/54 is merged. This PR works, however we should not update to another git dependency IMHO.
/cc @czosel

fix(deps): update jexl

---

addon/lib/field.js
addon/services/validator.js
tests/helpers/validator-service-stub.js
tests/integration/components/cf-field-test.js
tests/unit/services/validator-test.js

fix(form): fix premature access to validators which are not yet fetched

---

addon/mixins/caluma-apollo-service-mixin.js

feat(multilang): add language header to caluma requests as well

---

addon/components/cf-content.js
addon/components/cf-field-value.js
addon/components/cf-field/input/file.js
addon/components/cf-field/input/powerselect.js
addon/components/cf-field/input/table.js
addon/components/cf-form.js
addon/components/cfb-form-editor/general.js
addon/components/cfb-form-editor/question-list.js
addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/validation.js
addon/components/cfb-form-list.js
addon/lib/field.js
addon/routes/edit.js
addon/routes/edit/questions/edit.js
addon/services/validator.js
tests/dummy/app/routes/demo/form.js
tests/dummy/app/routes/index.js

https://github.com/ember-graphql/ember-apollo-client/blob/master/CHANGELOG.md#v200-beta5---2019-08-19

fix(apollo): remove deprecated usage of query manager

---

config/ember-try.js

This should speed up the additional test stages :smile:

chore(ci): use yarn in the CI

---

addon/components/cf-content.js
docker-compose.yml
tests/dummy/app/routes/demo/form.js

The network policy property name was incorrect.

Fix caching

---

package.json
yarn.lock

chore(deps): update eslint from 6.1.0 to 6.3.0

---

addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/options.js
addon/gql/queries/form-editor-question.graphql
addon/templates/components/cfb-form-editor/question/options.hbs
tests/integration/components/cfb-form-editor/question/options-test.js
translations/de.yaml
translations/en.yaml
translations/fr.yaml

This works but - IMO - needs more discussion.

feat(options): add (un)archive to form-builder

---

package.json
yarn.lock

chore(deps): upgrade jexl to 2.2.0

---

addon/lib/navigation.js
addon/templates/components/cf-navigation.hbs

fix(navigation): fix navigation to show base form questions

---

addon/components/cf-field/input/table.js
addon/gql/mutations/remove-document.graphql

Hopefully, this will help with the historical API.

fix(table): remove row documents on delete

---

addon/components/cf-field/input/checkbox.js
addon/components/cf-field/input/powerselect.js
addon/components/cf-field/input/radio.js
addon/gql/fragments/field-question.graphql
addon/gql/queries/get-document-used-dynamic-options.graphql
addon/gql/queries/get-dynamic-options.graphql
addon/lib/field.js
addon/lib/question.js
addon/templates/components/cf-field/input/checkbox.hbs
addon/templates/components/cf-field/input/powerselect.hbs
addon/templates/components/cf-field/input/radio.hbs
tests/integration/components/cf-field/input-test.js
tests/integration/components/cf-field/input/checkbox-test.js
tests/integration/components/cf-field/input/powerselect-test.js
tests/integration/components/cf-field/input/radio-test.js
translations/de.yaml
translations/en.yaml
translations/fr.yaml

This is now ready for review, but not for merging since I want to discuss some things with the backend dudes first..

feat(form): handle old values of dynamic questions

---

LICENSE
README.md
package.json

BREAKING CHANGE: Since the LGPL license is more restrictive than MIT,
this is marked as breaking
Resolves #613

feat(license): switch license from MIT to LGPL-3.0-or-later

---

addon/components/cf-field/input/powerselect.js

This fixes a regression introduced in #586

fix(form): fix search for powerselect inputs

---

.dependabot/config.yml

Default reviewers are the same as before, if someone wants to be in there as well just say the word :smile:

chore(dependabot): add more specific dependabot configuration

---

.eslintrc.js
.npmignore
.travis.yml
README.md
package.json
testem.browserstack.js
testem.js
yarn.lock

IE and Edge are currently disabled since they cause failing tests. I'd like to first merge the initial setup and add those missing browsers later

chore(ci): use browserstack for testing browser compatibility

---

.dependabot/config.yml

Mixed up `allowed_updates` and `ignored_updates` in the initial PR

chore(dependabot): fix ignored packages

---

.travis.yml
package.json
yarn.lock

Failing build because of:
https://github.com/pretenderjs/FakeXMLHttpRequest/issues/54
https://github.com/pretenderjs/pretender/pull/280
Waiting for:
https://github.com/miragejs/miragejs/pull/227
Closes #676 
Closes #675 
Closes #679 
Closes #678

chore(deps): update dependencies

---

addon/templates/components/cf-field/info.hbs
addon/templates/components/cf-field/input/table.hbs
package.json
yarn.lock

This fixes an issue with the info dialogs that could not be opened a
second time.

fix(deps): update ember-uikit to v2.0.1

---

addon/services/validator.js
tests/unit/services/validator-test.js

fix(form): do not run validators on empty values

---

addon/utils/slugify.js
tests/unit/utils/slugify-test.js

Match new max-length of backend.
https://github.com/projectcaluma/caluma/pull/942

feat(utils): increase slugify max-length to 150

---

addon/components/cf-field/input/float.js
addon/components/cf-field/input/integer.js
addon/components/cf-field/input/text.js
addon/components/cf-field/input/textarea.js
addon/components/cf-field/label.js
addon/components/cf-navigation-item.js
addon/lib/navigation.js
addon/templates/components/cf-content.hbs
addon/templates/components/cf-field/info.hbs
addon/templates/components/cf-field/input/date.hbs
addon/templates/components/cf-field/input/file.hbs
addon/templates/components/cf-field/input/powerselect.hbs
addon/templates/components/cf-field/input/table.hbs
addon/templates/components/cf-field/label.hbs
addon/templates/components/cf-navigation-item.hbs
addon/templates/components/cf-navigation.hbs
tests/integration/components/cf-field/info-test.js
tests/integration/components/cf-field/input/date-test.js
tests/integration/components/cf-field/input/file-test.js
tests/integration/components/cf-field/input/float-test.js
tests/integration/components/cf-field/input/integer-test.js
tests/integration/components/cf-field/input/powerselect-test.js
tests/integration/components/cf-field/input/text-test.js
tests/integration/components/cf-field/input/textarea-test.js
translations/de.yaml
translations/en.yaml
translations/fr.yaml

* Add `for` property on labels
* Add hidden text and labels on icon buttons
* Add role heading and proper level on active navigation items

feat(a11y): various improvements for accessibility

---

.dependabot/config.yml
.eslintrc.js
addon/components/cf-content.js
addon/components/cf-field/input/powerselect.js
addon/components/cf-field/input/table.js
addon/components/cfb-form-editor/general.js
addon/components/cfb-form-editor/question-list.js
addon/components/cfb-form-editor/question-list/item.js
addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/options.js
addon/components/cfb-form-editor/question/validation.js
addon/components/cfb-form-list.js
addon/components/cfb-jexl-boolean-toggle-switch.js
addon/components/cfb-navigation.js
addon/components/cfb-toggle-switch.js
addon/lib/answer.js
addon/lib/field.js
addon/lib/navigation.js
addon/lib/question.js
addon/mixins/navigation-route.js
addon/routes/edit.js
addon/routes/edit/questions/edit.js
addon/services/navigation.js
package.json
tests/dummy/config/environment.js
tests/helpers/promise.js
tests/unit/utils/and-test.js
tests/unit/utils/or-test.js
yarn.lock

Closes #999 
Closes #993 
Closes #990 
Closes #978 
Closes #968

chore(deps): update various dependencies and resolve deprecations

---

addon/lib/field.js
addon/utils/jexl.js
package.json
tests/unit/utils/jexl-test.js
yarn.lock

https://github.com/TomFrost/Jexl/commit/eecff1632c374ec45385ba606761c603d6f53222 this commit broke our jexl utility

fix(deps): update jexl to 2.3.0

---

addon/components/cfb-form-editor.js
addon/components/cfb-form-editor/question-list.js
addon/gql/queries/search-question.graphql
addon/templates/components/cfb-form-editor.hbs
addon/templates/components/cfb-form-editor/question-list.hbs
app/templates/components/cfb-form-editor.js
app/templates/components/cfb-form-editor/question-list.js
package.json
tests/integration/components/cfb-form-editor-test.js
tests/integration/components/cfb-form-editor/question-list-test.js
translations/de.yaml
translations/en.yaml
yarn.lock

The paging wasnt done with an infinte scroll but a button to manually load more questions on click

feat(cfb): add paging to question list

---

addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/options.js
addon/components/cfb-form-list.js
addon/components/cfb-form-list/item.js
addon/gql/queries/form-list.graphql
addon/routes/application.js
addon/templates/components/cf-field/input/checkbox.hbs
addon/templates/components/cfb-form-editor/question-list/item.hbs
addon/templates/components/cfb-form-editor/question.hbs
addon/templates/components/cfb-form-list.hbs
addon/templates/components/cfb-form-list/item.hbs
app/templates/components/cfb-form-list.js
app/templates/components/cfb-form-list/item.js
package.json
tests/integration/components/cfb-form-list-test.js
tests/integration/components/cfb-form-list/item-test.js
translations/de.yaml
translations/en.yaml
yarn.lock

Add separate list for archived forms and labels for the form state

feat(cfb): add seperation between archived and active forms

---

.dependabot/config.yml
addon/components/cfb-form-editor/question.js
addon/components/cfb-form-editor/question/options.js
addon/templates/components/cfb-form-editor/question.hbs
addon/utils/and.js
addon/utils/or.js
ember-cli-build.js
index.js
package.json
tests/dummy/app/snippets/config/ember-cli-build.js
tests/dummy/app/templates/docs/index.md
tests/dummy/config/ember-intl.js
tests/dummy/mirage/scenarios/default.js
yarn.lock

fix(deps): update ember-changeset and ember-changeset-validations

---

addon/gql/fragments/field-question.graphql
addon/lib/answer.js
addon/lib/document.js
addon/lib/field.js
addon/lib/navigation.js
addon/lib/question.js
addon/mirage-graphql/schema.graphql
addon/templates/components/cf-navigation-item.hbs
addon/templates/components/cf-navigation.hbs
app/styles/_cf-navigation.scss
package.json
tests/unit/lib/data.js
tests/unit/lib/field-test.js
yarn.lock

Navigation items which have fields that have only default answers will be greyed out to indicate that the user didn't do anything there but will still show the state (check, times or question mark) to indicate the state of the data in there:

feat(nav): implement navigation states for default answers

---

addon/components/cfb-code-editor.js
addon/templates/components/cfb-code-editor.hbs
addon/templates/components/cfb-form-editor/question.hbs
app/components/cfb-code-editor.js
app/styles/ember-caluma.scss
app/templates/components/cfb-code-editor.js
ember-cli-build.js
index.js
package.json
tests/integration/components/cfb-code-editor-test.js
tests/integration/components/cfb-form-editor/question-test.js
yarn.lock

feat(form builder): add syntax highlighting for markdown and jexl

---

addon/components/cfb-form-editor/question-list/item.hbs
app/styles/cfb-form-editor/question-list/_item.scss

Fixes changes introduced here: https://github.com/uikit/uikit/commit/121bb4cd1149aabd12ce788c9c22903b4ce39c9a

fix(cfb): improve badge styling after uikit update

---

addon/components/task-button.js

@Yelinz you really need to test your code better. `taskSlug` is not an existing filter!

fix(task-button): fix filter for fetching the task

---

addon/components/cfb-form-editor/question-list/item.hbs
addon/components/cfb-form-editor/question-list/item.js
app/styles/cfb-form-editor/question-list/_item.scss
tests/integration/components/cfb-form-editor/question-list/item-test.js
translations/de.yaml
translations/en.yaml
translations/fr.yaml

Enhance question type markers in question list of form-
builder with additional styles for conditionally required
and hidden JEXL expressions.
Resolves: #1306

feat(cfb): mark conditionally required / hidden questions

---

packages/form/addon/components/cf-field/input/date.hbs
packages/form/tests/integration/components/cf-field/input/date-test.js

fix(form): fix readonly state of date input

---

packages/form-builder/addon/components/cfb-form-editor/question.hbs

fix(form-builder): fix missing translation for row form select

---

packages/-ember-caluma/mirage/scenarios/default.js
packages/form-builder/addon/components/cfb-form-editor/question/options.js

@derrabauke FYI, minor regression of #1576

fix(form-builder): fix reordering of options and option slugs in mirage

---

packages/form/addon/modifiers/autoresize.js
packages/form/app/modifiers/autoresize.js

fix(form): fix textarea size in tables

---

packages/form-builder/addon/components/cfb-form-list.hbs
packages/form-builder/addon/components/cfb-form-list.js
packages/form-builder/addon/controllers/index.js
packages/form-builder/addon/templates/index.hbs
packages/form-builder/tests/acceptance/form-list-test.js
packages/form-builder/tests/integration/components/cfb-form-list-test.js
packages/form-builder/translations/de.yaml
packages/form-builder/translations/en.yaml
packages/form-builder/translations/fr.yaml
packages/testing/addon-mirage-support/factories/form.js
packages/testing/addon/mirage-graphql/filters/form.js
packages/testing/addon/scenarios/distribution.js

Add new category filters "published" and "unpublished" to the form list and make sure the filters and the search are stored in a query param for direct links.

feat(form-builder): add new categories published and unpublished

---

packages/core/addon/caluma-query/models/index.js

fix(core): handle null values in raw dates

---

package.json
packages/-ember-caluma/package.json
packages/core/package.json
packages/distribution/package.json
packages/form-builder/package.json
packages/form/package.json
packages/testing/package.json
packages/workflow/package.json
yarn.lock

chore(deps): update ember-cli-mirage

---

.github/workflows/deploy.yml
.github/workflows/release.yml
.github/workflows/test.yml

This speeds up our CI pipelines by about 50% :tada:

chore(ci): fix cache

---

packages/form-builder/addon/components/cfb-code-editor.js
packages/form-builder/addon/components/cfb-form-editor/question.hbs
packages/form-builder/addon/components/cfb-form-editor/question.js
packages/form-builder/tests/integration/components/cfb-code-editor-test.js
packages/form-builder/translations/de.yaml
packages/form-builder/translations/en.yaml
packages/form-builder/translations/fr.yaml

I was bored so I decided to fix #578 :man_shrugging:

feat(form-builder): add field for editing meta

---

packages/distribution/addon/components/inquiry-dialog.js
packages/distribution/addon/components/inquiry-dialog/inquiry-deadline.hbs
packages/distribution/addon/components/inquiry-dialog/inquiry-deadline.js
packages/distribution/addon/components/inquiry-dialog/inquiry-part.hbs
packages/distribution/addon/components/inquiry-dialog/inquiry-part.js
packages/distribution/addon/gql/mutations/withdraw-inquiry.graphql
packages/distribution/addon/gql/queries/inquiry-navigation.graphql
packages/distribution/addon/utils/unique-by-groups.js
packages/distribution/tests/integration/components/inquiry-dialog-test.js
packages/distribution/tests/integration/components/inquiry-dialog/inquiry-deadline-test.js
packages/distribution/translations/de.yaml
packages/distribution/translations/en.yaml
packages/distribution/translations/fr.yaml
packages/testing/addon/mirage-graphql/mocks/work-item.js
packages/testing/addon/scenarios/distribution.js

feat(distribution): add functionality to withdraw an inquiry

---

packages/form/addon/components/cf-field.hbs
packages/form/addon/components/cf-field.js
packages/form/addon/helpers/format-graphql-error.js
packages/form/app/helpers/format-graphql-error.js
packages/form/tests/integration/components/cf-field-test.js
packages/form/tests/integration/helpers/format-graphql-error-test.js
packages/form/translations/de.yaml
packages/form/translations/en.yaml
packages/form/translations/fr.yaml

feat(form): show technical details of backend errors in UI

---

packages/-ember-caluma/app/services/caluma-options.js
packages/distribution/addon/components/cd-inquiry-dialog.js
packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.hbs
packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.js
packages/distribution/addon/components/cd-truncated.hbs
packages/distribution/addon/components/cd-truncated.js
packages/distribution/addon/config.js
packages/distribution/addon/controllers/application.js
packages/distribution/addon/gql/fragments/inquiry.graphql
packages/distribution/addon/gql/queries/inquiry-dialog.graphql
packages/distribution/addon/templates/application.hbs
packages/distribution/app/components/cd-truncated.js
packages/distribution/app/styles/@projectcaluma/ember-distribution.scss
packages/distribution/app/styles/_truncated.scss
packages/distribution/tests/helpers/inquiry.js
packages/distribution/tests/integration/components/cd-inquiry-dialog/inquiry-part-test.js
packages/distribution/tests/integration/components/cd-inquiry-dialog/inquiry-test.js
packages/distribution/tests/integration/components/cd-truncated-test.js
packages/distribution/tests/unit/config-test.js
packages/distribution/translations/de.yaml
packages/distribution/translations/en.yaml
packages/distribution/translations/fr.yaml
packages/testing/addon/scenarios/distribution.js

feat(distribution): allow displaying more information in the answer

---

packages/core/addon/caluma-query/index.js
packages/core/addon/caluma-query/resource.js
packages/distribution/addon/components/cd-inquiry-answer-form.js
packages/distribution/addon/components/cd-inquiry-dialog.js
packages/distribution/addon/components/cd-inquiry-edit-form.js
packages/distribution/addon/components/cd-inquiry-new-form.js
packages/distribution/addon/services/distribution.js
packages/form-builder/addon/components/cfb-form-editor/general.js
packages/form-builder/addon/components/cfb-form-editor/question/validation.js
packages/form/addon/components/cf-content.js
packages/form/addon/lib/question.js
packages/workflow/addon/components/task-button.js

This fixes all deprecations described in the migration guide of `ember-resources`: https://github.com/NullVoxPopuli/ember-resources/blob/main/MIGRATIONS.md

fix(resources): fix deprecations of ember-resources

---

packages/form/addon/components/cf-field/input/checkbox.hbs
packages/form/addon/components/cf-field/input/radio.hbs
packages/form/addon/lib/field.js
packages/form/tests/integration/components/cf-field/input/checkbox-test.js
packages/form/tests/integration/components/cf-field/input/radio-test.js
packages/form/tests/unit/lib/field-test.js
packages/form/translations/de.yaml
packages/form/translations/en.yaml
packages/form/translations/fr.yaml

- Display the label of the faulty option in the error message
- Don't accept disabled options as valid values in validation
- Disable inputs of disabled options

fix(form): improve validation of choice and multiple choice fields

---

packages/distribution/package.json
packages/form-builder/package.json
yarn.lock

Reverts projectcaluma/ember-caluma#1984

Revert "chore(deps): bump ember-engines-router-service from 0.3.0 to 0.4.0"

---

docker-compose.yaml
packages/distribution/addon/gql/fragments/inquiry.graphql
packages/distribution/addon/gql/mutations/complete-inquiry-work-item.graphql
packages/form-builder/addon/gql/mutations/add-form-question.graphql
packages/form-builder/addon/gql/mutations/remove-form-question.graphql
packages/form-builder/addon/gql/mutations/reorder-form-questions.graphql
packages/form-builder/addon/gql/queries/check-form-slug.graphql
packages/form-builder/addon/gql/queries/check-question-slug.graphql
packages/form-builder/addon/gql/queries/form-editor-general.graphql
packages/form-builder/addon/gql/queries/form-editor-question.graphql
packages/form-builder/addon/gql/queries/search-form-question.graphql
packages/form-builder/addon/routes/edit.js
packages/form-builder/addon/routes/edit/questions/edit.js
packages/form/addon/gql/queries/document-forms.graphql
packages/form/addon/gql/queries/dynamic-options.graphql
packages/testing/addon/mirage-graphql/filters/base.js
packages/testing/addon/mirage-graphql/schema.graphql
packages/testing/tests/unit/mirage/filters/base-test.js
packages/testing/tests/unit/mirage/mocks/form-test.js
packages/testing/tests/unit/mirage/mocks/question-test.js

BREAKING CHANGE: `ember-caluma` now requires Caluma version >= 8.0.0-beta.6

feat(caluma): use new filter syntax of caluma

---

.github/workflows/release.yml

Adds the analytics package to the release job.

chore: add analytics package to releases

---

packages/form/addon/components/cf-field/input/checkbox.hbs
packages/form/tests/integration/components/cf-field/input/checkbox-test.js

fix(form): allow deselecting disabled multiple choice options

---

packages/-ember-caluma/app/app.js
packages/-ember-caluma/app/services/fetch.js
packages/core/addon/services/-scheduler.js
packages/distribution/addon/abilities/distribution.js
packages/distribution/addon/components/cd-navigation/controls.hbs
packages/distribution/addon/components/cd-navigation/controls.js
packages/distribution/addon/engine.js
packages/distribution/addon/gql/mutations/redo-work-item.graphql
packages/distribution/addon/gql/queries/control-work-items.graphql
packages/distribution/addon/services/distribution.js
packages/distribution/tests/integration/components/cd-navigation-test.js
packages/distribution/tests/integration/components/cd-navigation/controls-test.js
packages/distribution/translations/de.yaml
packages/distribution/translations/en.yaml
packages/distribution/translations/fr.yaml
packages/testing/addon-mirage-support/factories/work-item.js
packages/testing/addon/mirage-graphql/mocks/work-item.js
packages/testing/addon/mirage-graphql/schema.graphql
packages/testing/addon/scenarios/distribution.js

Include control work-item to reopen distribution and
associated control button and ability.

feat(distribution): add functionality to reopen distribution

---

packages/analytics/addon/components/ca-field-select.hbs

Adds search to analytics field selects

fix(analytics): add search to field select

---

packages/-ember-caluma/package.json
packages/analytics/package.json
packages/core/package.json
packages/distribution/addon/components/cd-inquiry-dialog.hbs
packages/distribution/addon/components/cd-inquiry-dialog/inquiry-divider.hbs
packages/distribution/addon/components/cd-navigation/controls.hbs
packages/distribution/addon/components/cd-navigation/status-indicator.hbs
packages/distribution/package.json
packages/distribution/tests/helpers/uikit.js
packages/distribution/tests/integration/components/cd-inquiry-dialog/inquiry-divider-test.js
packages/distribution/tests/integration/components/cd-navigation/status-indicator-test.js
packages/distribution/tests/test-helper.js
packages/form-builder/addon/components/cfb-form-editor/question-list/item.hbs
packages/form-builder/package.json
packages/form/package.json
packages/workflow/package.json
yarn.lock

Needs https://github.com/adfinis/ember-uikit/pull/922 to be released

fix(uikit): use modifier of ember-uikit for tooltips

---

packages/analytics/addon/components/ca-report-builder.hbs
packages/analytics/addon/components/ca-report-builder.js
packages/analytics/translations/de.yaml
packages/analytics/translations/en.yaml
packages/analytics/translations/fr.yaml

Add `DOCUMENTS` and `WORK_ITEMS` startingOptions to reflect the schema

fix(analytics): update startingOptions to reflect schema

---

packages/-ember-caluma/package.json
packages/analytics/package.json
packages/form-builder/addon/components/cfb-form-editor/question.hbs
packages/form-builder/addon/components/cfb-form-editor/question.js
packages/form-builder/package.json
yarn.lock

fix(form-builder): show columns of row form to display properly

---

packages/distribution/addon/components/cd-inquiry-new-form.hbs
packages/distribution/addon/components/cd-navigation.hbs
packages/distribution/addon/components/cd-navigation/controls.hbs
packages/distribution/addon/components/cd-navigation/controls.js
packages/distribution/addon/components/cd-navigation/item.hbs
packages/distribution/addon/components/cd-navigation/section.hbs
packages/distribution/addon/services/distribution.js
packages/distribution/addon/templates/application.hbs
packages/distribution/addon/templates/index.hbs
packages/distribution/tests/integration/components/cd-navigation-test.js
packages/distribution/tests/integration/components/cd-navigation/item-test.js
packages/distribution/tests/integration/components/cd-navigation/section-test.js
packages/distribution/translations/de.yaml
packages/distribution/translations/en.yaml
packages/distribution/translations/fr.yaml

- Change translations for sections
- Hide sections without content
- Hide navigation on index page if no inquiries exist

feat(distribution): improve navigation

---

packages/distribution/addon/abilities/distribution.js
packages/distribution/addon/components/cd-navigation/controls.hbs
packages/distribution/addon/components/cd-navigation/controls.js
packages/distribution/addon/config.js
packages/distribution/addon/gql/queries/control-work-items.graphql
packages/distribution/addon/services/distribution.js
packages/distribution/tests/integration/components/cd-inquiry-dialog-test.js
packages/distribution/tests/integration/components/cd-navigation/controls-test.js
packages/distribution/tests/unit/config-test.js
packages/distribution/translations/de.yaml
packages/distribution/translations/en.yaml
packages/distribution/translations/fr.yaml
packages/testing/addon/scenarios/distribution.js

feat(distribution): add button to mark inquiries as checked

---

packages/distribution/addon/components/cd-inquiry-dialog.js
packages/distribution/addon/services/distribution.js

fix(distribution): make sure the inquiry dialog data is always fetched from the backend

---

packages/distribution/addon/abilities/inquiry.js
packages/distribution/tests/integration/components/cd-inquiry-new-form-test.js
packages/distribution/tests/unit/abilities/inquiry-test.js

- Only allow editing sent inquiries if sending would be allowed
- Make sure answer form can't be edited without a ready complete workflow form work item
- Refactor inquiry ability for better readability

fix(distribution): fix various inquiry permissions

---

packages/distribution/addon/abilities/inquiry.js
packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.js
packages/distribution/addon/components/cd-inquiry-edit-form.hbs
packages/distribution/tests/unit/abilities/inquiry-test.js

Include custom edit inquiry permission in inquiry
abilities and improve inquiry views for users
without edit permission.

fix(distribution): custom edit inquiry permission

---

packages/form/addon/components/cf-content.js
packages/form/addon/gql/queries/dynamic-options.graphql
packages/form/addon/lib/document.js
packages/form/addon/lib/field.js
packages/form/addon/lib/question.js
packages/testing/addon/mirage-graphql/schema.graphql

Needs https://github.com/projectcaluma/caluma/pull/1917

feat(form): use cf-content context for fetching and saving dynamic questions

---

packages/distribution/addon/config.js
packages/distribution/addon/utils/inquiry-status.js
packages/distribution/tests/unit/config-test.js

feat(distribution): allow custom inquiry status icon and color config

---

.github/dependabot.yml
packages/-ember-caluma/package.json
packages/analytics/package.json
packages/distribution/package.json
packages/form-builder/package.json
yarn.lock

https://github.com/ember-engines/ember-engines/issues/833

chore(deps): downgrade ember-engines

---

packages/analytics/addon/components/ca-field-selector-list.hbs
packages/analytics/addon/components/ca-field-selector-list.js
packages/analytics/addon/gql/mutations/reorder-analytics-fields.graphql
packages/analytics/translations/de.yaml
packages/analytics/translations/en.yaml
packages/analytics/translations/fr.yaml

Implements reordering for analytics fields.
Depends on https://github.com/projectcaluma/caluma/issues/1889

feat(analytics): implement reordering of fields

---

packages/-ember-caluma/config/environment.js
packages/distribution/tests/integration/components/cd-inquiry-new-form-test.js
packages/form/addon/components/cf-field/input/date.hbs
packages/form/addon/components/cf-field/input/date.js
packages/form/tests/integration/components/cf-content-test.js
packages/form/tests/integration/components/cf-field/input/date-test.js

Fix various bugs with the date input
Fixes #2233

fix(form): use alt input with flatpickr

---

packages/form-builder/addon/validations/question.js
packages/form-builder/addon/validators/meta.js
packages/form-builder/tests/unit/validators/meta-test.js

add meta validation
code editor returns a string when its not a valid javascript object

feat(form-builder): add meta validation

---

packages/analytics/addon/gql/mutations/reorder-analytics-fields.graphql

sorting resets when switching from preview to fields otherwise

fix(analytics): fetch sorted analytics table for watchquery

---

packages/form/addon/components/cf-field.hbs
packages/form/addon/components/cf-field.js
packages/form/addon/lib/question.js

fix(form): reload dynamic options when field enters the viewport

---

packages/-ember-caluma/mirage/scenarios/default.js
packages/form-builder/translations/de.yaml
packages/form-builder/translations/en.yaml
packages/form-builder/translations/fr.yaml
packages/form/addon/components/cf-field-value.hbs
packages/form/addon/components/cf-field/input/number-separator.hbs
packages/form/addon/components/cf-field/input/number-separator.js
packages/form/addon/instance-initializers/form-widget-overrides.js
packages/form/app/components/cf-field/input/number-separator.js
packages/form/tests/integration/components/cf-field-value-test.js
packages/form/tests/integration/components/cf-field/input/number-separator-test.js

feat(form): add widget override for number separator

---

packages/analytics/addon/components/ca-report-preview.hbs
packages/analytics/addon/components/ca-report-preview.js
packages/analytics/package.json
packages/analytics/tests/integration/components/ca-report-preview-test.js
packages/analytics/translations/de.yaml
packages/analytics/translations/en.yaml
packages/analytics/translations/fr.yaml
pnpm-lock.yaml

Export your analytics preview table as Excel.

feat(analytics): excel export of reports table

---

packages/form/app/styles/_flatpickr.scss
packages/form/package.json
packages/form/tests/integration/components/cf-field/input/action-button-test.js
pnpm-lock.yaml

dependents seem to have problems with importing the form styles (errors with not found), but not analytics or others. The difference I spotted between was form not having sass as any dependency.

chore(form): add missing sass dev dependencies

---

packages/distribution/addon/gql/queries/controls.graphql
packages/testing/addon/mirage-graphql/filters/base.js

fix(distribution): remove deprecated case id filter

---

packages/form/addon/lib/document.js
packages/form/tests/unit/lib/document-test.js

Needs https://github.com/projectcaluma/caluma/pull/2278

feat(jexl): add length transform

---

package.json
pnpm-lock.yaml

Removed any inflector v4 which causes webpack errors
error which happens without this change
```sh
ERROR in ../../../../../../tmp/broccoli-3721228nXjKmAAamc27/cache-1115-webpack_bundler_ember_auto_import_webpack/app.cjs 49:138-186
Module not found: Error: Can't resolve 'ember-inflector/lib/helpers/pluralize' in '/tmp/broccoli-3721228nXjKmAAamc27/cache-1115-webpack_bundler_ember_auto_import_webpack'
resolve 'ember-inflector/lib/helpers/pluralize' in '/tmp/broccoli-3721228nXjKmAAamc27/cache-1115-webpack_bundler_ember_auto_import_webpack'
Parsed request is a module
No description file found in /tmp/broccoli-3721228nXjKmAAamc27/cache-1115-webpack_bundler_ember_auto_import_webpack or above
resolve as module
looking for modules in /tmp/broccoli-3721228nXjKmAAamc27/cache-1115-webpack_bundler_embe …
```

fix(deps): override ember-inflector to use auto-import v2

---

packages/analytics/addon/components/ca-report-preview.hbs
packages/analytics/addon/components/ca-report-preview.js

exports do not include white space currently
This should fix that

fix(analytics): preserve whitespace for exports

---

packages/form/addon/lib/field.js

Previous commit was incorrectly set as chore, not triggering a release. Undo the commit in this MR before I open a new one

Revert "chore(jexl): revert JEXL evaluation condition"

---

packages/form/addon/lib/field.js

Same change as a fix instead of chore now

fix(jexl): revert JEXL evaluation condition

---

packages/-ember-caluma/package.json
pnpm-lock.yaml

chore(deps): update @embroider/macros
