- .eslintrc.js
- addon/components/cf-field/input.js
- addon/components/cf-field/input/powerselect.js
- addon/components/cfb-form-editor/question.js
- addon/gql/fragments/field-question.graphql
- addon/gql/fragments/question-info.graphql
- addon/templates/components/cf-field/input/powerselect.hbs
- addon/templates/components/cfb-form-editor/question.hbs
- app/components/cf-field/input/powerselect.js
- app/styles/_cfb-powerselect.scss
- app/styles/ember-caluma.scss
- config/deploy.js
- ember-cli-build.js
- package.json
- tests/dummy/config/environment.js
- tests/integration/components/cf-field/input/powerselect-test.js
- translations/de-de.yaml
- translations/en-us.yaml
- yarn.lock
Powered by [Ember Power Select](https://ember-power-select.com/)
* Current threshold for search field is at 3 choices.
* Currently not styled through UIkit.
* `searchMessage` seems to be overridden by `noMatchesMessage` (see [API reference](https://ember-power-select.com/docs/api-reference/))
> Custom widgets for single and multiple choice questions

- CHANGELOG.md
- addon/engine.js
- tests/dummy/app/app.js
- tests/dummy/app/snippets/usage/app.js
- tests/dummy/app/templates/docs/index.md
**Do not merge this before the consuming apps have been changed!**
This fixes the missing translations by requesting the `intl` service from the host app.
Additionally, this change adds the dependency to the dummy app to avoid having an error, when running the add-on standalone.
> FIX missing dependency transmission

- addon/components/cf-field/input.js
- addon/components/cfb-form-editor/question.js
- addon/mirage-graphql/schema.graphql
Since https://github.com/projectcaluma/caluma/pull/318, the meta field
returns an actual object (GenericScalar) instead of a JSONString.
> Adapt meta field handling to latest caluma release

- blueprints/ember-caluma/index.js
In order for sass imports to work in the consuming app,
ember-power-select needs to be installed in the app.
> Add ember-power-select to blueprint

- docker-compose.yml
This allows us to "link" the frontend with a specific version of the
backend container. In the future, we will probably use tags instead of
digests.
> Docker: Reference caluma container by digest

- addon/mixins/caluma-apollo-service-mixin.js
- package.json
- yarn.lock
Implemented the same way a JWT Bearer token would be.
**From my experience ember-intl uses all lower-case letters for the language codes.**
e.g. `de-CH` would be `de-ch`
Resolves #54
> ADD Accept-Language header with locale from ember-intl

- addon/components/cf-form.js
As we manually validate our form input, the native validations range from nuisance to problem.
Firefox is especially annoying as it adds a red box-shadow to invalid fields.
> FIX native form validation interference

- addon/components/cf-form.js
This allows passing a computed property as documentId which is initially
null.
> Cf-form: Use didReceiveAttrs instead of willRender

- addon/services/document-store.js
- tests/unit/services/document-store-test.js
Before, it was not possible to override an existing entry in the
document store, which can cause issues if the same document is requested
and passed to `find()` twice (The document store would return the old
built document).
By switching to an object we can also make sure that each document is
only present once in the cache.
> Document store: use map instead of array, add save method

- addon/components/cfb-form-editor/question.js
- addon/components/cfb-form-editor/question/options.js
- addon/templates/components/cfb-form-editor/question/options.hbs
- tests/integration/components/cfb-form-editor/question-test.js
Currently, we're overwriting manual slug changes (made by the user) when
the label is changed afterwards. This is not great UX.
> Stop updating slug on label change after manual slug changes

- blueprints/ember-caluma/index.js
It seems that even if a helper is only used inside the addon, the addon providing it still needs to be installed in the host app.
> Add missing peer dependencies

- addon/styles/addon.scss
- addon/templates/components/cfb-form-editor/question.hbs
- package.json
- yarn.lock
This aims to make the jexl field in the form builder a bit more pleasant
to work with by allowing multiline expressions and rendering it with a
monospace font.
Multiline support in JEXL has already been added in the past, but was
(i suppose unintentionally) lost during the 2.0 release. See
https://github.com/TomFrost/Jexl/pull/54 for details.
pyJexl already supports multiline expressions.
> feat(jexl): add support for multiline expressions

- addon/components/cf-field-value.js
- addon/gql/fragments/field-answer.graphql
- addon/templates/components/cf-field-value.hbs
- translations/de-de.yaml
I left out the extra query to the caluma backend for the moment. We can add it later if it turns out to be needed.
> fix(table): render download links for file questions in tables

- addon/styles/addon.scss
Falling back to the default Pikaday z-index of `9999`.
Rather bad practice but let's fix the z-indexes when we have more time.
> REMOVE custom z-index

- addon/templates/components/cf-field/info.hbs
We had some issues with the "drop" element (positioning, width), so
we'll go with the slightly less elegant but also more stable modal.
> fix(info): replace drop by modal

- addon/lib/document.js
- addon/lib/question.js
- tests/unit/lib/question-test.js
New: When evaluating JEXL, you can also use `root` as a path
element for your slug, which will then start at the top-level
document.
Also, improve error reporting if a path cannot be resolved:
We can now report exactly the position where it failed
Note this is the equivalent of projectcaluma/caluma#414
> Add "root" to doc slug lookups, improve reporting

- addon/lib/document.js
- addon/lib/question.js
- tests/unit/lib/document-test.js
This fixes some subtle issue that occur when once field depends on
multiple other fields:
1) The field's JEXL expression only doesn't have to be calculated, if
_all_ fields it depends on are hidden (not just one!)
2) If some of the fields it depends on are hidden, those fields should
behave as if they were unanswered, even if the have an answer in the
database.
> fix(jexl): don't consider the value of hidden fields in JEXL expr.

- package.json
- tests/dummy/app/routes/index.js
- tests/dummy/app/routes/nested.js
- yarn.lock
After wasting _way_ too much time with trying to get ember-auto-import to transpile jexl automatically, I decided to take the easy way out by downgrading Jexl to the latest 1.x commit that also contains the PR introducing whitespace support.
> fix(deps): downgrade to jexl 1.x for IE 11 compat

- addon/components/cf-navigation.js
Not sure if `finally` is the right place.
The reasoning is that I cannot add it at the end of the `try` block as there are `return`s before that. My problem with `finally` is that it will scroll on error which might be confusing.
> Scroll to top on document change

- translations/de-de.yaml
- translations/en-us.yaml
Because those fields are supposed to be used not only for static
content, but also for custom component overrides. Calling it "Non-interactive"
hopefully makes this more obvious.
> chore(naming): rename "static field" to "non-interactive" field

- addon/components/cf-form.js
- addon/components/cf-navigation.js
- addon/templates/components/cf-field.hbs
- addon/templates/components/cf-form.hbs
- addon/templates/components/cf-navigation.hbs
This is useful to allow passing "context" data to custom components.
> feat(cf-form): allow passing context information to cf-form, cf-navigation

- addon/lib/document.js
Without this, the hidden state of fields considered in the "state"
computation of navigation entries "lags" behind it's actual value.
> fix(cf-navigation): add compute watcher on hidden state

- addon/components/cf-field/input/table.js
- addon/lib/answer.js
- addon/lib/document.js
- addon/lib/field.js
- addon/lib/question.js
- tests/unit/lib/document-test.js
>  feat(jexl): support jexl referencing TableQuestions

- addon/components/cf-field/input/table.js
- addon/components/cfb-form-editor/question.js
- addon/gql/queries/form-editor-question.graphql
- addon/templates/components/cf-field/input/table.hbs
- addon/templates/components/cfb-form-editor/question.hbs
- translations/de-de.yaml
- translations/en-us.yaml
> feat: add table column display configuration

- addon/components/cf-field/input/powerselect.js
This is not using "includes" but strict equality checking to determine
which option is selected. Without this fix, the wrong option is rendered
when one option key is contained in another option key, because
String.includes is called instead of Array.includes.
> fix(powerselect): render correct slected option for choice questions

- package.json
Those two dependencies are handled by https://github.com/adfinis-sygroup/semantic-release-config/ which is already a dependency. If we remove them we only have to maintain one dependency instead of three.
PS: `yarn.lock` didn't change because the dependency stays the same since `@adfinis-sygroup/semantic-release-config` currently references the same version we had
> chore(deps): remove obsolete dependencies

- package.json
- yarn.lock
This PR removes `ember-cli-eslint` and moves to using plain `eslint` for linting js files. Since `yarn lint:js` runs plain `eslint` anyways we can drop the ember implementation. This will result in a lot less Qunit test. Also this resolves the [problem with updating `eslint-plugin-prettier`](https://github.com/ember-cli/ember-cli-eslint/issues/235)
Resolves #34
> chore(eslint): remove ember-cli-eslint and move to plain eslint

- addon/templates/components/cfb-form-editor/question-list.hbs
- package.json
I think we should remove this dependency since it's not widely used in our addon..
Closes #318
> fix(deps): remove dependency to liquid-fire

- package.json
- yarn.lock
[This was needed for node v6 support](https://github.com/projectcaluma/ember-caluma/commit/2c142e395a50f1414330fbe2192ae1232505c274), which we don't support anymore since it's not an LTS anymore.
> fix(deps): remove tough-cookie resolution

- addon/components/cf-field/input/table.js
- addon/gql/fragments/field-answer.graphql
- addon/lib/answer.js
- addon/lib/document.js
- addon/lib/field.js
- addon/templates/components/cf-field/input/table.hbs
- tests/integration/components/cf-field/input/table-test.js
This allows us to handle table questions like we handle all other types. Updating client state then becomes obsolete since the save response automatically triggers the update of the computed property.
10/10 would merge!
> fix(table): fix answer handling of table questions

- addon/lib/field.js
This makes sure that the answer has a uuid property which computes to `answer.raw.id`
> fix(form): fix removing of empty answers

- addon/components/cf-content.js
- addon/lib/document.js
- addon/lib/field.js
- addon/lib/fieldset.js
- addon/lib/navigation.js
This makes sure that if `cf-content` is being destroyed it destroys all lib objects containing data or state with it in the proper order.
> fix(lib): fix teardown of lib objects

- addon/lib/field.js
Currently, saving an empty value in a field with no previous value errors.
> fix(field): don't delete non-existent answers

- addon-mirage-support/factories/option.js
- addon/components/cf-field/input/radio.js
- addon/gql/fragments/field-question.graphql
- tests/dummy/mirage/scenarios/default.js
- tests/integration/components/cf-content-test.js
This change will hide archived options from the public forms.
The changes for the form-builder will come in a different PR:
> feat(options): hide archived options

- addon/components/cfb-form-editor/question-list/item.js
- addon/lib/field.js
- addon/lib/question.js
- addon/utils/jexl.js
- tests/unit/utils/jexl-test.js
This is now possible since whitespace support was added in the latest
version
> chore(jexl): remove obsolete jexl cleaning functions

- addon/components/cf-content.js
- addon/components/cf-field-value.js
- addon/components/cf-field/input/file.js
- addon/components/cf-field/input/powerselect.js
- addon/components/cf-field/input/table.js
- addon/components/cf-form.js
- addon/components/cfb-form-editor/general.js
- addon/components/cfb-form-editor/question-list.js
- addon/components/cfb-form-editor/question.js
- addon/components/cfb-form-editor/question/validation.js
- addon/components/cfb-form-list.js
- addon/lib/field.js
- addon/routes/edit.js
- addon/routes/edit/questions/edit.js
- addon/services/validator.js
- tests/dummy/app/routes/demo/form.js
- tests/dummy/app/routes/index.js
`ember-apollo-client`'s `queryManager` breaks IE11 currently. To fix
this we now use the deprecated mixins. This can be reverted, as soon as
https://github.com/ember-graphql/ember-apollo-client/issues/303 is
resolved.
> fix(ie11): remove usage of queryManager which breaks in IE11

- addon/templates/components/cfb-form-editor/question/options.hbs
- tests/integration/components/cfb-form-editor/question/options-test.js
This change only presents the possibility to delete options as long as they are not saved to the database.
PS: This PR will not work as-is. It needs the changes from #515
> fix(cfb-options): options cannot be deleted from db

- addon/components/cf-field/input/table.js
Saving the existing rows does nothing except messing up the revision history.
> fix(table): don't re-save existing rows after edit

- addon/components/cf-field-value.js
Currently, an empty/missing date is displayed as "Invalid Date".
> fix(table): skip empty dates in table view

- .travis.yml
- README.md
- config/ember-try.js
BREAKING CHANGE: This will remove the support for the second last LTS
version of ember, since we support only the last LTS version which is
3.12 now.
> chore: remove support for ember 3.8

- addon/gql/mutations/remove-answer.graphql
- addon/lib/field.js
- addon/mirage-graphql/schema.graphql
This adds compatibility for
https://github.com/projectcaluma/caluma/pull/791. Instead of removing
answers with an empty value, we now save the empty value.
BREAKING CHANGE: Only works with caluma v4.0.0 (https://github.com/projectcaluma/caluma/pull/791)
> feat(form): allow empty values for answers

- addon/lib/answer.js
- tests/integration/components/cf-field-test.js
StringAnswer is the only answer type that could have multiple types of
empty answers:
- empty string
- null
Since every other answer type can only have null as empty answer we now
transform empty strings to null to be consistent.
> fix(form): transform empty string answers to null

- .travis.yml
- config/ember-try.js
- package.json
- testem.js
Running tests now looks like this:
Failed tests would be below the dot matrix with a clear error
> chore(ci): add firefox to test matrix and use more compact reporter

- .travis.yml
Secret variables can't be used in jobs triggered by PRs of forks.
Therefore the browserstack tests will fail because the connection fails.
https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
> chore(ci): do not run browserstack tests on forks

- addon/components/cf-field/input/float.js
- addon/components/cf-field/input/integer.js
- addon/components/cf-field/input/text.js
- addon/components/cf-field/input/textarea.js
- addon/templates/components/cf-field/input/file.hbs
- addon/templates/components/cf-field/input/table.hbs
- app/styles/_uikit-overwrites.scss
- app/styles/ember-caluma.scss
- tests/integration/components/cf-content-test.js
- tests/integration/components/cf-field-test.js
- tests/integration/components/cf-field/input-test.js
- tests/integration/components/cf-field/input/float-test.js
- tests/integration/components/cf-field/input/integer-test.js
- tests/integration/components/cf-field/input/text-test.js
- tests/integration/components/cf-field/input/textarea-test.js
IIRC, the reasoning for this one goes like this:
* it’s impossible to copy text out of a disabled field in Firefox, which is problematic in one of our projects
* readonly fields look like they can be edited, which is bad UX
-> this is changing disabled fields to readonly ones, but styles them like disabled fields.
> fix: change disabled to readonly where applicable

- addon/lib/field.js
See
https://github.com/projectcaluma/caluma/commit/81cbe9aae553ed91a86c1813a47085fb3b386713
> Since graphql-core doesn't support `null` literals yet, the way for
setting the value of an Answer to `None` is to omit the `value` field
altogether.
> fix(field): don't pass `value` to save mutation if null

- addon/lib/field.js
FormAnswer was removed from Caluma, so no reason to still use it.
> fix: remove FormAnswer

- addon/components/cf-content.js
- addon/components/cf-field/input/table.js
- addon/initializers/caluma-models.js
- addon/lib/answer.js
- addon/lib/document.js
- addon/lib/field.js
- addon/lib/fieldset.js
- addon/lib/navigation.js
- app/initializers/caluma-models.js
- package.json
- tests/integration/components/cf-field-test.js
- tests/integration/components/cf-field/input/powerselect-test.js
- tests/integration/components/cf-field/label-test.js
- tests/unit/initializers/caluma-models-test.js
- tests/unit/lib/answer-test.js
- tests/unit/lib/document-test.js
- tests/unit/lib/field-test.js
- tests/unit/lib/fieldset-test.js
- tests/unit/lib/form-test.js
- tests/unit/lib/question-test.js
- yarn.lock
Apparently this is the best practice for creating application context
for custom ember objects. This removes all usage of the weirdly
undocumented `ownerInjection`.
> refactor(lib): register caluma models on the registry

- addon/lib/document.js
This allows using a parent field answer in a JEXL of a table question
> feat(form): include parent fields in find field method

- addon/lib/document.js
- addon/lib/field.js
- package.json
- tests/unit/lib/document-test.js
- tests/unit/lib/field-test.js
Depends on https://github.com/projectcaluma/caluma/pull/978
```js
{
form: rootFormSlug,
info: {
form: currentFormSlug,
parent: { form: parentFormSlug },
root: { form: rootFormSlug }
}
}
```
`info.root.form == "root-form"`
`info.parent.form == "parent-form"`
`info.form == "current-form"`
Legacy JEXL expressions will still work through:
`form == "root-form"`
> feat(jexl): add info object to context

- .github/workflows/test.yml
- config/dependency-lint.js
- package.json
- yarn.lock
Depends on #1003 
This tool makes sure that only one version of a dependency is installed. It can also be used to say what version. This will help us maintain this addon since the dependency problem already bit us in the ass a couple of times..
> chore(ci): add dependency linting

- addon/templates/components/cf-field/input/powerselect.hbs
Without this no options are rendered if ember-caluma is embedded.
> fix(embed): render power select in place

- blueprints/ember-caluma/index.js
This is required so we can use the helpers from ember-composable-helpers.
Im not sure why this is needed in the first place. The same was already
done in commit 8319c63 for other dependencies.
> fix(blueprints): add ember-composable-helpers to host app dependencies

- addon/caluma-query/queries/base.js
- tests/dummy/app/templates/docs/queries.md
This allows dynamic filtering via `queryOptions` since the decorator has no way to recompute the value of queryOptions.
Im still leaving in the decorator param since this can be still usefull for options that do not change.
> refactor(caluma-query): allow `queryOptions` to be set on `fetch`

- CHANGELOG.md
- package.json
* **caluma-query:** allow `queryOptions` to be set on `fetch` ([547d08d](https://github.com/projectcaluma/ember-caluma/commit/547d08d7897d85242a8524b61bc0d2a494f4cfa8))
> chore(release): 6.4.0

- addon/components/cf-field/input.js
- addon/helpers/get-widget.js
In one of our projects we ran into the issue that `typename` was
undefined during the loading of the page. This fix makes sure that we
don't fail in this situation.
This also includes a drive-by fix that prevents incorrect component
registration warnings.
> fix(form): don't throw when typename is undefined in cf-field/input

- addon/lib/document.js
The passed value is logged to console and then passed along
for further chaining.
Closes #1095
> feat(lib): add a debug transform which logs to console

- addon/components/cf-field/input/powerselect.js
- config/environment.js
- tests/dummy/config/environment.js
For some use-cases 10 options is too late to show the search.
> feat(cf-field): make options limit configurable

- addon/components/cf-field/input/powerselect.js
- config/environment.js
Apparently, the pattern with configuring a default config in
`config/environment.js` doesn't work as documented and no major ember
addon uses this pattern. This broke every app that didn't configure the
`powerSelectEnableSearchLimit` option.
> fix(config): fix power select limit default config

- addon/components/cf-field/input.js
- addon/components/cf-field/input/float.js
- addon/components/cf-field/label.js
- addon/gql/fragments/field-question.graphql
- addon/lib/field.js
- addon/lib/question.js
- addon/templates/components/cf-field/input/float.hbs
- addon/templates/components/cf-field/label.hbs
- app/templates/components/cf-field/input/float.js
- app/templates/components/cf-field/label.js
- package.json
- tests/integration/components/cf-field/input-test.js
- tests/integration/components/cf-field/input/float-test.js
- tests/unit/lib/data.js
- tests/unit/lib/document-test.js
- tests/unit/lib/field-test.js
This commit also refactors the float input and label components to glimmer components since I had to touch them.
Depends on #1173
> feat(form): show calculated fields in form and compute their value live

- addon/components/cfb-form-editor/question.js
- addon/components/cfb-form-editor/question/default.js
- addon/gql/mutations/remove-default-answer.graphql
- addon/gql/mutations/save-default-date-answer.graphql
- addon/gql/mutations/save-default-float-answer.graphql
- addon/gql/mutations/save-default-integer-answer.graphql
- addon/gql/mutations/save-default-list-answer.graphql
- addon/gql/mutations/save-default-string-answer.graphql
- addon/gql/mutations/save-default-table-answer.graphql
- addon/gql/queries/form-editor-question.graphql
- addon/lib/field.js
- addon/mirage-graphql/index.js
- addon/mirage-graphql/mocks/answer.js
- addon/mirage-graphql/mocks/base.js
- addon/mirage-graphql/resolvers/index.js
- addon/templates/components/cf-field/input/date.hbs
- addon/templates/components/cfb-form-editor/question.hbs
- addon/templates/components/cfb-form-editor/question/default.hbs
- app/components/cfb-form-editor/question/default.js
- tests/integration/components/cfb-form-editor/question/default-test.js
- translations/de.yaml
- translations/en.yaml
- translations/fr.yaml
This will create/update/delete default answers which will be used when rendering a form to fill out.
> feat(cfb): add input for default values

- addon/components/cfb-form-editor/question/default.js
This adds a decorator to the field getter to stop Ember from recalculating the property too often.
`@computed("question", "value", "value.content", "model.slug")`
would technically be enough. The other properties are there to satisfy a linting rule.
> fix(cfb): fix recalculation issue in default values

- addon/components/cfb-form-editor/question-list.js
- addon/components/cfb-form-editor/question/options.js
- addon/templates/components/cfb-form-editor/question/options.hbs
- translations/de.yaml
- translations/en.yaml
Allows reordering options of Choice or MultipleChoice questions, by dragging and dropping. Similar to reordering Questions.
New options aren't reorder able, as they have no slug before saving.
closes  #1086
> feat(cfb): implement reordering of question options

- package.json
- yarn.lock
For some reason 7.12.13 fails to transpile TypeScript sources.
At least ember-intl but this is probably just because it's the
first package alphabetically.
> fix(deps): add resolution to fix @babel/parser to 7.12.11

- addon/components/cfb-form-editor/question/default.js
Widget overrides from the questions should not be considered for this
component. We manually set an override for choices but otherwise, we
use the real input type.
> fix(question/default): ignore question's widgetOverride

- addon/lib/document.js
- tests/unit/lib/document-test.js
Calculating the average of an empty array would result in a `0/0`
division. `null` has to be returned in that case instead of `NaN`.
> fix(jexl): fix division by 0 in avg transform

- addon/lib/field.js
- addon/lib/navigation.js
Otherwise, there's no other way than do go though all (sub-)forms
to check where the missing question is located.
> fix(lib/navigation): don't set state to empty if fields are required

- addon/lib/document.js
- tests/unit/lib/document-test.js
We need to validate numbers differently since `null` `""` `true`
and `false` are not `NaN` and therefore a validation with `isNaN()`
is pretty much useless.
> fix(jexl): fix validation of numbers in transforms

- addon/lib/dependencies.js
The `field.value` is empty when no document exists for a table question. Only try to gather the fields if a document/value exists, otherwise this field is of no interest.
Fixes #1235
> fix(jexl): fix jexl dependency gathering for empty tables

- addon/lib/field.js
For example `StaticQuestion` has no answer, therefore the field value should be handled accordingly.
> fix(field): some questions do not have an answer, handle this correctly

- package.json
- yarn.lock
With newer versions of Node, `ember-cli-browserstack` needs a minor fix
for opening the connection to browserstack:
https://github.com/kategengler/ember-cli-browserstack/pull/40
> chore(tests): fix browserstack connection creation

- addon/caluma-query/models/form.js
- addon/caluma-query/queries/form.js
- addon/caluma-query/queries/index.js
- addon/components/cfb-form-list.js
- addon/initializers/caluma-query-models.js
- addon/mirage-graphql/filters/base.js
- addon/mirage-graphql/filters/form.js
- addon/mirage-graphql/mocks/base.js
- addon/mirage-graphql/serializers/form.js
- addon/templates/components/cfb-form-list.hbs
- tests/acceptance/form-list-test.js
- tests/integration/components/cfb-form-list-test.js
- translations/de.yaml
- translations/en.yaml
Add the capability of searching for specific form names among the
listed forms. Paginate the retrieved forms and allow to load more
forms on demand.
> feat(cfb): implement search and pagination of form list

- .github/workflows/test.yml
- README.md
- config/ember-try.js
- package.json
- tests/dummy/config/ember-cli-update.json
- yarn.lock
BREAKING CHANGE: This removes guaranteed support for ember LTS 2.20 and
adds guaranteed support for the newly active LTS 2.24
> chore(deps)!: drop support for older ember LTS version 2.20

- addon/components/cf-field/input/file.js
- tests/integration/components/cf-field/input/file-test.js
Replace XMLHttpRequest implementation for file
uploads with fetch API.
Resolves #593
> refactor(cf): use fetch API for file uploads

- addon/lib/dependencies.js
- addon/lib/document.js
- addon/utils/jexl.js
- tests/unit/lib/data.js
- tests/unit/lib/document-test.js
- tests/unit/lib/field-test.js
This extends the mapby transform to accept multiple keys as argument
which then returns an array instead of the single value. This will
result in nested arrays which is why we added a stringify transform that
converts such a collection into a string to be used in comparisons.
> feat(jexl): improve mapby and add stringify transform

- addon/components/cfb-form-editor/question-list.js
- addon/routes/edit.js
- addon/routes/edit/questions/edit.js
- addon/services/validator.js
- package.json
- yarn.lock
ember-concurrency v2+ uses tracked properties in the background. Sadly, we're not quite ready to enforce this so we readd the decorators addon to enable usage of ember-caluma with a prior version
> fix: use concurrency decorators for compatibility

- .github/workflows/test.yml
- package.json
- yarn.lock
The issue that made us downgrade moment has been fixed in
ember-moment-shim 3.8.0.
https://github.com/adopted-ember-addons/ember-pikaday/issues/343
> chore(deps): upgrade momentjs

- .github/workflows/deploy.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
This seems to be the only way to clear the node modules cache in GitHub
actions...
I changed all of the occurrences to fix the release workflow.
> chore: clear node modules cache

- addon/lib/dependencies.js
- addon/lib/document.js
- addon/lib/field.js
- tests/unit/lib/document-test.js
- tests/unit/lib/field-test.js
This allows the user to write reusable JEXLs using answer transforms that don't necessarily resolve to a question in a certain form context.
https://github.com/projectcaluma/caluma/pull/1536
> feat(jexl): allow optional answer transforms with default value

- addon/components/cf-field/input/file.js
It seems that minio expects the request body to be the plain file
instead of a FormData object.
This fixes a regression introduced in #1287.
> fix(file upload): don't use formdata for minio upload

- package.json
Prism v1.24 has been released, and the update was performed in #1460
:tada:
> chore: remove note about prism.js from package.json

- blueprints/ember-caluma/index.js
Seems like I messed up earlier and the project I tested with had ember-in-viewport installed without me noticing.
> fix: add ember-in-viewport to blueprint

- addon/components/cfb-form-editor/question.hbs
- addon/components/cfb-form-editor/question.js
- addon/mirage-graphql/mocks/question.js
- app/styles/cfb-form-editor/_question.scss
- app/styles/ember-caluma.scss
- tests/integration/components/cfb-form-editor/question-test.js
- translations/de.yaml
- translations/en.yaml
- translations/fr.yaml
When building table and form questions in the
form-builder, the selection of available sub- or
rowforms is searchable and displays the name of
the form in addition to the slug.
Resolves: #1299
Example view:
Matches form slug field:
> feat(cfb): make sub- & rowforms searchable

- tests/dummy/app/router.js
- translations/dummy/de.yaml
- translations/dummy/en.yaml
- translations/dummy/fr.yaml
Currently when making a fresh copy of the git repo the documentation in the dummy repo doesn't actually show anything because the "validation" route is missing from `router.js`.
I added the route and added the required translations in the dummy app.
> fix(demo-app): added required "validation" route to router and added translations

- addon/components/task-button.hbs
- addon/components/work-item-button.js
- tests/dummy/app/templates/docs/buttons.md
- tests/integration/components/work-item-button-test.js
This will allow the user to pass an action that is executed before the mutation starts. E.g displaying a confirmation dialog.
> feat(buttons): add willMutate hook for work item and task buttons

- addon-mirage-support/factories/question.js
- addon/components/cfb-form-editor.hbs
- addon/components/cfb-form-editor/question-list.hbs
- addon/components/cfb-form-editor/question-list/item.hbs
- addon/components/cfb-form-editor/question-list/item.js
- addon/controllers/edit.js
- addon/gql/queries/search-form-question.graphql
- addon/gql/queries/search-question.graphql
- addon/routes/edit.js
- addon/templates/edit.hbs
- tests/acceptance/question-link-form-test.js
- tests/integration/components/cfb-form-editor/question-list-test.js
For table and form questions add direct link to subform
or rowform in question list. Show correct path and
question list corresponding to sub- / rowform.
Resolves: #1416
> feat(cfb): link sub- & rowforms in question list

- addon/components/document-validity.hbs
- addon/components/document-validity.js
- tests/dummy/app/templates/docs/validation.md
- tests/integration/components/document-validity-test.js
BREAKING CHANGE: The `validateOnEnter` parameter for the `DocumentValidity` component is now `false` instead of `true` since this is the default use case.
> feat(validation): switch default for validateOnEnter

- packages/-ember-caluma/app/app.js
- packages/-ember-caluma/app/snippets/usage/app.js
- packages/form-builder/addon/components/cfb-navigation.js
- packages/form-builder/addon/controllers/edit.js
- packages/form-builder/addon/controllers/edit/questions/edit.js
- packages/form-builder/addon/controllers/edit/questions/new.js
- packages/form-builder/addon/controllers/index.js
- packages/form-builder/addon/controllers/new.js
- packages/form-builder/addon/engine.js
- packages/form-builder/package.json
- packages/form-builder/tests/dummy/app/app.js
- yarn.lock
https://deprecations.emberjs.com/v3.x#toc_routing-transition-methods
We now use `ember-engines-router-service` to have an engine internal router service instead of using the host router service. The `router` in the engine configuration can now be removed.
> fix(form-builder): remove deprecated usage of transitionToRoute

- .husky/commit-msg
The previously used `pre-commit` hook has no access to the current commit message. `yarn commitlint --edit $1` will fallback to `.git/COMMIT_EDITMSG` in case the argument passed (here `$1`) was undefined. BUT `.git/COMMIT_EDITMSG` references the commit message of the last (successful) commit, not the current one.
`$1` is always undefined for `pre-commit` hooks in husky.
`$1` contains the path to the file of the current commit message when used in `commit-msg` hook.
> Today I learned something. 🤓👍
> fix(linting): separate husky commit-msg hook

- .template-lintrc.js
- packages/form-builder/tests/integration/components/cfb-form-editor/question/default/table-test.js
- packages/form/addon/components/cf-field/input/table.hbs
- packages/form/addon/components/cf-field/input/table.js
- packages/form/tests/integration/components/cf-field/input/table-test.js
- packages/form/translations/de.yaml
- packages/form/translations/en.yaml
- packages/form/translations/fr.yaml
- packages/testing/addon/mirage-graphql/mocks/base.js
- Refactor to glimmer and simplify table input component
- Add indicator to invalid rows
- Add close button in edit mode
- Add cancel button in add mode
- Cleanup orphaned rows when cancelling in add mode
- Only enable save button if document is valid
- Add missing tests for table inputs, resolves #455
> feat(form): refactor table to glimmer and add invalid indicator

- packages/-ember-caluma/app/controllers/demo/form-rendering.js
- packages/-ember-caluma/app/services/caluma-options.js
- packages/-ember-caluma/app/templates/demo/form-rendering.hbs
- packages/-ember-caluma/mirage/scenarios/default.js
- packages/core/addon/-private/possible-types.js
- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/addon/gql/fragments/field-question.graphql
- packages/form-builder/addon/gql/mutations/save-action-button-question.graphql
- packages/form-builder/addon/gql/queries/form-editor-question.graphql
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form/addon/components/cf-field.hbs
- packages/form/addon/components/cf-field.js
- packages/form/addon/components/cf-field/input.hbs
- packages/form/addon/components/cf-field/input.js
- packages/form/addon/components/cf-field/input/action-button.hbs
- packages/form/addon/components/cf-field/input/action-button.js
- packages/form/addon/gql/fragments/field-question.graphql
- packages/form/addon/gql/queries/get-document-answers.graphql
- packages/form/addon/lib/document.js
- packages/form/addon/lib/field.js
- packages/form/app/components/cf-field/input/action-button.js
- packages/form/package.json
- packages/form/tests/integration/components/cf-field/input/action-button-test.js
- packages/testing/addon-mirage-support/factories/question.js
- packages/testing/addon-mirage-support/models/document.js
- packages/testing/addon/mirage-graphql/mocks/base.js
- packages/testing/addon/mirage-graphql/schema.graphql
Add a new question type for action buttons that render a button for completing or skipping the work item related to the current document.
Backend implementation: https://github.com/projectcaluma/caluma/pull/1607
> feat(form): add new question type action button

- config/ember-try.js
- packages/form/addon/components/document-validity.js
Ember v4 is now officially released. However, we're not quite ready for this so we allow the `ember-release` to fail for now.
> chore(ci): allow ember-release scenario to fail

- packages/form-builder/addon/gql/fragments/field.graphql
- packages/form/addon/gql/fragments/field.graphql
This change is needed as the symlink doesnt show up in the package,
which breaks queries in the form-builder package.
> fix: replace fragment symlink with a copy

- packages/testing/addon/mirage-graphql/filters/base.js
- packages/testing/tests/unit/mirage/filters/base-test.js
Given this GraphQL query:
```graphql
query Forms {
allForms(filter: [{}]) {
edges {
node {
id
}
}
}
}
```
would cause the mirage filter to fail:
`Cannot read properties of undefined (reading '0')`
This MR includes the fix as well as 1 extra test.
Please note: I only added 1 line. The rest is just indentation change.
> fix: passing an empty object in a filter array does not cause a crash

- .eslintrc.js
- packages/-ember-caluma/app/services/apollo.js
- packages/-ember-caluma/app/snippets/apollo.js
- packages/-ember-caluma/app/templates/docs/index.md
- packages/-ember-caluma/app/templates/docs/migration-v11.md
- packages/core/addon/services/apollo.js
- packages/core/app/services/apollo.js
- packages/core/package.json
- packages/core/tests/unit/services/apollo-test.js
- packages/distribution/tests/dummy/app/services/apollo.js
- packages/form-builder/tests/dummy/app/services/apollo.js
- packages/form/tests/dummy/app/services/apollo.js
- packages/workflow/tests/dummy/app/services/apollo.js
BREAKING CHANGE: The apollo service mixin was removed in favor of
directly overriding the service. For more information on how to migrate,
please visit the v11 migration guide.
Resolves #529
> fix(core): override apollo service instead of serving a mixin

- packages/form/addon/components/cf-field-value.js
- packages/form/addon/components/cf-field/input/file.js
This fixes the graphql "Invariant Violation: 10" error which occurs,
when trying to download a file answer through the table header
> fix(form): change file download actions to query and network-only

- packages/form/addon/components/cf-field/input/action-button.hbs
- packages/form/addon/components/cf-field/input/action-button.js
- packages/form/tests/integration/components/cf-field/input/action-button-test.js
Only use the default button type "button" for action
buttons. Using button type "submit" can lead to issues
on browsers such as firefox, where the default submit
action is triggered.
> fix(form): use action button type "button"

- packages/form/addon/lib/navigation.js
Set the state of a parent form to valid if there is a subform with only
static questions.
> fix(navigation): exclude static questions from visible fields

- packages/-ember-caluma/app/services/caluma-options.js
- packages/core/addon/services/caluma-options.js
- packages/core/package.json
- packages/form-builder/addon/instance-initializers/form-builder-widget-overrides.js
- packages/form-builder/app/instance-initializers/form-builder-widget-overrides.js
- packages/form-builder/tests/unit/instance-initializers/form-builder-widget-overrides-test.js
- packages/form/addon/components/cf-field.hbs
- packages/form/addon/components/cf-form-wrapper.hbs
- packages/form/addon/helpers/get-widget.js
- packages/form/addon/instance-initializers/form-widget-overrides.js
- packages/form/app/instance-initializers/form-widget-overrides.js
- packages/form/tests/integration/helpers/get-widget-test.js
- packages/form/tests/unit/instance-initializers/form-widget-overrides-test.js
- yarn.lock
This is needed so widget overrides can be used in an engine since the engine can't resolve the component by name.
> feat(form): support passing component override classes

- docker-compose.yaml
- packages/-ember-caluma/mirage/scenarios/default.js
- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/addon/gql/fragments/field.graphql
- packages/form-builder/addon/gql/mutations/save-calculated-float-question.graphql
- packages/form-builder/addon/gql/mutations/save-choice-question.graphql
- packages/form-builder/addon/gql/mutations/save-date-question.graphql
- packages/form-builder/addon/gql/mutations/save-dynamic-choice-question.graphql
- packages/form-builder/addon/gql/mutations/save-dynamic-multiple-choice-question.graphql
- packages/form-builder/addon/gql/mutations/save-file-question.graphql
- packages/form-builder/addon/gql/mutations/save-float-question.graphql
- packages/form-builder/addon/gql/mutations/save-integer-question.graphql
- packages/form-builder/addon/gql/mutations/save-multiple-choice-question.graphql
- packages/form-builder/addon/gql/mutations/save-table-question.graphql
- packages/form-builder/addon/gql/mutations/save-text-question.graphql
- packages/form-builder/addon/gql/mutations/save-textarea-question.graphql
- packages/form-builder/addon/gql/queries/form-editor-question.graphql
- packages/form-builder/addon/validations/question.js
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form/addon/components/cf-field.hbs
- packages/form/addon/components/cf-field.js
- packages/form/addon/components/cf-field/hint.hbs
- packages/form/addon/gql/fragments/field.graphql
- packages/form/app/components/cf-field/hint.js
- packages/form/tests/integration/components/cf-field/hint-test.js
- packages/testing/addon/mirage-graphql/schema.graphql
Add option to create hints for certain question types. These
are displayed below the input field and can be used to provide
short, informative messages. Hints are available for all question
types except for form, static and action button questions.
> feat(cf-field): add optional hints for form fields

- bin/update-cross-dependencies.mjs
- packages/form/addon/components/cf-field/input/action-button.hbs
- packages/form/addon/components/cf-field/input/action-button.js
- packages/form/package.json
This is mostly playing around with embroider, but can't hurt :man_shrugging:
To answer the question everyone will have from the beginning, here's the [RFC about optional peer dependencies](https://emberjs.github.io/rfcs/0507-embroider-v2-package-format.html#optional-peer-dependencies) and the [yarn docs](https://classic.yarnpkg.com/en/docs/package-json#peerdependenciesmeta-).
> chore(action-button): exclude action button from build if workflow is not installed

- packages/form-builder/addon/components/cfb-code-editor.js
- packages/form-builder/index.js
- packages/form-builder/package.json
- yarn.lock
This is to prevent them from clashing in the addon docs, as they use the
same tags.
How the form-builder editors with highlighting look like now
fixes #1864
> fix(form-builder): replace prismjs with highlight.js

- packages/-ember-caluma/package.json
- packages/core/package.json
- packages/distribution/addon/components/cd-navigation/controls.hbs
- packages/distribution/addon/components/cd-navigation/controls.js
- packages/distribution/addon/gql/mutations/complete-work-item.graphql
- packages/distribution/addon/gql/queries/incomplete-inquiries.graphql
- packages/distribution/package.json
- packages/distribution/tests/integration/components/cd-navigation/controls-test.js
- packages/distribution/translations/de.yaml
- packages/distribution/translations/en.yaml
- packages/distribution/translations/fr.yaml
- packages/form-builder/package.json
- packages/form/package.json
- packages/testing/addon/mirage-graphql/mocks/work-item.js
- packages/testing/package.json
- packages/workflow/package.json
- yarn.lock
Add functionality to complete the running distribution.
If incomplete inquiries (ready or suspended) remain on
the current distribution, a confirmation dialog will
appear. Add side effects in mirage-graphql to cancel
all remaining incomplete inquiries.
> feat(distribution): enable completing the distribution

- packages/distribution/addon/components/cd-document-header.hbs
- packages/distribution/addon/components/cd-inquiry-answer-form.hbs
- packages/distribution/addon/components/cd-inquiry-answer-form.js
- packages/distribution/addon/components/cd-inquiry-dialog/inquiry-deadline.hbs
- packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.hbs
- packages/distribution/addon/components/cd-inquiry-edit-form.hbs
- packages/distribution/addon/components/cd-inquiry-new-form.hbs
- packages/distribution/addon/gql/fragments/inquiry.graphql
- packages/distribution/addon/gql/queries/inquiry-answer.graphql
- packages/distribution/addon/gql/queries/inquiry-dialog.graphql
- packages/distribution/addon/gql/queries/inquiry-edit.graphql
- packages/distribution/app/components/cd-document-header.js
- packages/distribution/app/styles/@projectcaluma/ember-distribution.scss
- packages/distribution/app/styles/_answer-form.scss
- packages/distribution/tests/integration/components/cd-document-header-test.js
- packages/distribution/tests/integration/components/cd-inquiry-answer-form-test.js
- packages/distribution/tests/integration/components/cd-inquiry-dialog/inquiry-part-test.js
- packages/distribution/tests/integration/components/cd-inquiry-edit-form-test.js
- packages/distribution/translations/de.yaml
- packages/distribution/translations/en.yaml
- packages/distribution/translations/fr.yaml
- packages/testing/addon-mirage-support/factories/document.js
- packages/testing/addon/scenarios/distribution.js
Answer inquiry with new title design and request as context:
Edit inquiry with new title design:
New inquiry with new title design:
Inquiry dialog with new "detail" links for a readonly view of the filled form:
> feat(distribution): improve edit and answer inquiry UI and UX

- packages/distribution/addon/components/cd-inquiry-dialog.hbs
- packages/distribution/addon/components/cd-inquiry-dialog.js
- packages/distribution/addon/components/cd-inquiry-new-form.js
- packages/distribution/addon/components/cd-navigation/controls.hbs
- packages/distribution/addon/services/distribution.js
- packages/distribution/tests/integration/components/cd-inquiry-dialog-test.js
This adds a button to create a new inquiry for the target group of the current dialog directly in the dialog itself.
> feat(distribution): add button to create new inquiry in dialog

- packages/distribution/addon/components/cd-inquiry-answer-form.js
- packages/distribution/addon/gql/queries/inquiry-answer.graphql
Refetch inquiry answer after work-item completion and include
closedAt work-item field in the graphql query to ensure the
completion date is updated correctly in the inquiry answer
dialog.
> fix(distribution): refetch inquiry answer after work-item completion

- .github/pull_request_template.md
After an *off the record* discussion, we came to the conclusion that we want to have a PR template, which reminds devs to list dependencies to other pull requests and prevent ill-timed merges.
Most commonly this will be the case for features which have cohesive parts in the `ember-caluma` and the `caluma` repos.
> chore: add default pr template

- package.json
- yarn.lock
After latest dependency updates the CI went ok, but running the local docs app could not be accessed anymore. Until further investigation into the issue we downgrade the dependency.
Fixes # `Uncaught TypeError: decorator is not a function`
> fix(deps): resolve dep issue of ember-cli-addon-docs and tracked-toolbox

- packages/testing/addon-mirage-support/factories/form.js
- packages/testing/addon/mirage-graphql/filters/base.js
- packages/testing/tests/unit/mirage/filters/base-test.js
Currently it is not possible to filter by `createdBy` and `modifiedBy` filters on the miragejs backend.
This PR adds the `createdByUser`, `createdByGroup`, `modifiedByUser` and `modifiedByGroup` filters to the base filters.
No dependencies
> feat(testing): add createdBy and modifiedBy filters

- packages/testing/addon/mirage-graphql/filters/answer.js
- packages/testing/addon/mirage-graphql/filters/base.js
- packages/testing/addon/mirage-graphql/filters/work-item.js
- packages/testing/tests/unit/mirage/filters/answer-test.js
- packages/testing/tests/unit/mirage/filters/base-test.js
- packages/testing/tests/unit/mirage/filters/work-item-test.js
Implements the `invert` option of the real caluma backend.
No dependencies.
> feat(testing): allow inverting of filters

- packages/form/addon/components/cf-field/input/files.hbs
- packages/form/tests/integration/components/cf-field/input/files-test.js
When a field is disabled one could still trigger the delete file action.
Fixes #2084
> fix(files): disable delete button when field is disabled

- packages/analytics/addon/components/ca-field-selector-list.hbs
- packages/analytics/addon/components/ca-field-selector-list/ca-field-alias-input.hbs
- packages/analytics/addon/components/ca-field-selector-list/ca-field-alias-input.js
- packages/analytics/tests/integration/components/ca-field-selector-list/ca-field-alias-input-test.js
- packages/analytics/translations/de.yaml
use different icon as a checkmark is confusing
this looks like it has been auto saved, just like in the form
looks more something you have to click than before
as uikit doesnt have a classical save icon, which would be better, this just uses something similar
I'm open to suggestions to use a different icon
> fix(analytics): improve alias save

- packages/-ember-caluma/app/services/caluma-options.js
- packages/-ember-caluma/mirage/config.js
- packages/core/addon/services/caluma-options.js
- packages/distribution/addon/abilities/inquiry.js
- packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.hbs
- packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.js
- packages/distribution/addon/config.js
- packages/distribution/addon/gql/fragments/inquiry.graphql
- packages/distribution/addon/gql/queries/inquiry-meta.graphql
- packages/distribution/addon/utils/inquiry-deadline.js
- packages/distribution/tests/helpers/inquiry.js
- packages/distribution/tests/integration/components/cd-inquiry-dialog/inquiry-part-test.js
- packages/distribution/tests/unit/config-test.js
- packages/distribution/translations/de.yaml
- packages/distribution/translations/en.yaml
- packages/distribution/translations/fr.yaml
- packages/testing/addon/scenarios/distribution.js
Add a configurable functionality for sending reminders on overdue inquiries. A list of previous reminders are displayed and need to be updated through the meta field on the inquiry.
Co-authored-by: Jonas Metzener <jonas.metzener@adfinis.com>
> feat(distribution): enable reminders for overdue inquiries

- packages/form/addon/lib/field.js
Similar to regular choice questions, dynamic choice question options should not be validated if they have no answer.
> fix: dynamic choice validation

- packages/distribution/addon/components/cd-inquiry-dialog.js
Currently the user will be redirected to the first inquiry that already exists, not the one that was just created. If we refresh the dialog query after creating we have current data and the redirect works as expected.
> fix(distribution): fix redirect after inquiry creation in dialog

- packages/form-builder/addon/validations/question.js
Integer questions currently can't be saved without setting a min and max value, because the validation deems undefined an invalid value
> fix(cfb): fix min, max being invalid when empty

- packages/form-builder/addon/components/cfb-form-editor/question/default.js
Fixes bug with choice question default anwers.
When selecting a default answer, the change isn't reflected by the dropdown. Saving throws an error, but produces a change in the backend. Initial loading doesn't show the saved answer.
> fix(cfb): fix choice question default answer not showing

- packages/form/addon/components/cf-field/input/date.js
without settings defaults it would always choose the en format, when the options arent configured
> fix(form): use defaults to mimic previous behaviour

- packages/form-builder/addon/components/cfb-form-editor/question.hbs
currently once a override widget is selected, it cant be removed unless meta is edited
> fix(form-builder): allow widget override to be removed

- packages/-ember-caluma/package.json
- packages/analytics/addon/components/ca-field-selector-list.hbs
- packages/analytics/addon/components/ca-field-selector-list.js
- packages/analytics/addon/components/ca-filter-modal.hbs
- packages/analytics/app/styles/@projectcaluma/ember-analytics.scss
- packages/analytics/package.json
- packages/analytics/tests/integration/components/ca-field-selector-list-test.js
- packages/analytics/tests/integration/components/ca-report-builder-test.js
- yarn.lock
replace uikit sortable with ember-sortable
With uikit sortable the table can break when dragging to specific locations
With ember-sortable it works and uses modifieres which is nice and relativly easily testable
> fix(analytics): fix table reordering breaking the table

- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/tests/integration/components/cfb-form-editor/question-test.js
Currently, the options for widget overrides are not being loaded correctly when changing the question type. This means that any widget override that has a question type specified is not available.
[Screencast from 27.03.2023 16:42:30.webm](https://user-images.githubusercontent.com/88476449/227975707-d678c4fa-6cfb-40f8-a972-92d1276ddadd.webm)
[Screencast from 27.03.2023 16:45:04.webm](https://user-images.githubusercontent.com/88476449/227975674-f9ff7531-6f2a-4410-970b-e14d4d35a222.webm)
I think the issue is that we are creating the changeset in a getter:
```javascript
get changeset () {
return new Changeset(this.model, ...)
}
```
which messes up the reactivity when trying to watch changes on the changeset (I think?). Instead, I made the changeset a tracked property and initialise it after …
> fix: load the correct widget override options for a question

- packages/form/addon/components/cf-field.hbs
We want to customize the layout of our caluma form. Therefore we have to identify the form field component, especially the wrapping `div`. Currently only the inputs are contextualized with the field/question id. Since CSS `:has` is not supported in Firefox yet, we have to mark the wrapping element as well.
> feat(form): add data attributes for better field identification

- packages/form/addon/components/cf-field.js
- packages/form/addon/lib/field.js
- Dynamic options *must* be refetched before validation
- Dynamic options should only be refetched on viewport enter if they were already fetched once. Otherwise initial fetching will be done twice.
- Used dynamic options should only be fetched if the dynamic options are resolved. Otherwise it will always fetch them as the value is initially unknown (while the dynamic options are being fetched)
> fix(form): fix validation of dynamic option

- .github/workflows/release.yaml
- bin/bump-version.mjs
- package.json
- pnpm-lock.yaml
`release-it` doesn't work properly with `pnpm` so we dropped it in favor of our normal release tool `semantic-release`. However, that doesn't really work with monorepos and pnpm, so I added a little bit of customization:
1. The version bump is done via a node script since there is no good `semantic-release` plugin to do that in monorepos
2. The publish step is done via pnpm CLI to make sure the cross dependency versions are properly resolved
> chore(release): fix release in CI

- packages/form-builder/addon/components/cfb-form-editor/question/default.js
This allows to disable the powerselect widget override that is active by default in the form builder.
> feat: allow to disable the powerselect override in the form builder

- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/addon/gql/mutations/save-action-button-question.graphql
- packages/form-builder/addon/gql/queries/form-editor-question.graphql
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form/addon/components/cf-field/input/action-button.hbs
- packages/form/addon/components/cf-field/input/action-button.js
- packages/form/tests/integration/components/cf-field/input/action-button-test.js
- packages/form/translations/de.yaml
- packages/form/translations/en.yaml
- packages/form/translations/fr.yaml
- packages/testing/addon-mirage-support/factories/question.js
- packages/testing/addon/mirage-graphql/schema.graphql
Add the possibility to show invalid fields for the action-button widget.
Depends on https://github.com/projectcaluma/caluma/pull/2050
> feat(validation): list invalid fields for the action-button widget

- packages/distribution/addon/components/cd-inquiry-new-form/bulk-edit.hbs
Pass the selectedGroups as a context prop to the form wrapper in an inquiry (we need this for a customer because we need to use a widget override for the date)
> feat: pass selectedGroups as context to form wrapper in inquiry form

- packages/form/addon/components/cf-field/input/checkbox.js
- packages/form/tests/integration/components/cf-field/input/checkbox-test.js
This fixes an issue where the value of a checkbox question was not properly updated to the answer model and therefore the backend. This happened because the save task uses a timeout to debounce value saving. As the update function of the component always used the value from the user model this caused a race condition if the user clicked the options too fast.
> fix(form): fix fast selection in checkboxes

- packages/distribution/addon/components/cd-inquiry-dialog/inquiry-part.js
- packages/distribution/addon/components/cd-truncated.hbs
- packages/distribution/addon/gql/fragments/inquiry-answer.graphql
- packages/testing/addon/mirage-graphql/index.js
This enables the inquiry preview for single and multiple choice questions:
> feat: enable single- and multiple-choice questions in the inquiry preview

- packages/distribution/addon/abilities/distribution.js
Passes the `distribution` coming from the `distribution` service to any provided permission functions.
This allows the consumer to do things like this:
```javascript
const permissions = {
completeDistribution: ({ navigation }) => {
const specialPrivilegedGroup = ['1'];
return navigation.value.controlling.edges.any(({node}) =>
node.addressedGroups.includes(specialPrivilgedGroup));
})
}
```
and therefore showing/hiding buttons depending on the state of the distribution.
> feat(distribution): pass distribution to abilities functions

- packages/core/addon/services/-scheduler.js
- packages/core/package.json
- pnpm-lock.yaml
Calling `.toArray` on ember-data arrays is deprecated since `ember-data@4.7.0`. Therefore we make the `.toArray` call conditional.
> fix: add ember-data version check to check if calling `.toArray` on ember-data arrays is deprecated

- packages/form/addon/components/cf-field.hbs
- packages/form/addon/components/cf-field.js
- packages/form/translations/de.yaml
- packages/form/translations/en.yaml
- packages/form/translations/fr.yaml
Currently, we always show a technical error message when an answer could not be saved, even if it is due to an incorrect validation (which is not a technical error). In this MR, this gets slightly reworked to show some more detailed information:
(i just doctored the text in which is why there is no actual technical infos shown but the MR doesnt touch that bit)
> feat: show better error message for failing validations

- package.json
- packages/-ember-caluma/package.json
- packages/analytics/package.json
- packages/core/package.json
- packages/distribution/package.json
- packages/form-builder/package.json
- packages/form/package.json
- packages/workflow/package.json
- pnpm-lock.yaml
This fixes the compatibility tests but not the embroider scenarios. We'll tackle that later on.
For more information see https://github.com/embroider-build/embroider/issues/1169#issuecomment-1156803926 and https://github.com/ember-cli/ember-try?tab=readme-ov-file#pnpm
> chore(pnpm): use injected to fix package resolution issues

- packages/distribution/addon/templates/index.hbs
- packages/distribution/translations/de.yaml
- packages/distribution/translations/en.yaml
- packages/distribution/translations/fr.yaml
The current text on the distribution index page is misleading when no actions are available
> fix(distribution): improve text when no action is available

- packages/form-builder/addon/components/cfb-form-editor/question-usage.hbs
- packages/form-builder/addon/components/cfb-form-editor/question-usage.js
- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/gql/queries/all-forms-for-question.graphql
- packages/form-builder/app/components/cfb-form-editor/question-usage.js
- packages/form-builder/tests/acceptance/question-usage-test.js
- packages/form-builder/tests/integration/components/cfb-form-editor/question-usage-test.js
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form-builder/translations/fr.yaml
This MR introduces a new modal which shows in which form a question is being used (and if that form is archived or not published).
(I'm not sure about the label)
> feat: modal which shows in which form the question is used

- packages/form-builder/addon/components/cfb-form-editor/question-usage.js
- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/tests/integration/components/cfb-form-editor/question-usage-test.js
Currently a change in the question triggers a re-fetching of all the forms where this question is used. (Maybe because changeset replaces the tracked object instead of updating its property? Not sure)
To prevent this we simply assign the result of the graphql query to a tracked array and re-use this when the trackedFunction is called again.
> fix(form-builder): don't refetch the forms for "used by" modal on changeset update

- packages/form-builder/addon/components/cfb-form-editor/cfb-advanced-settings.hbs
- packages/form-builder/addon/components/cfb-form-editor/cfb-advanced-settings.js
- packages/form-builder/addon/components/cfb-form-editor/general.hbs
- packages/form-builder/addon/components/cfb-form-editor/general.js
- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/gql/fragments/form-info.graphql
- packages/form-builder/app/components/cfb-form-editor/cfb-advanced-settings.js
Allows editing of form meta (similar to the question meta).
> feat(form-builder): allow editing of form meta

- packages/form/tests/integration/components/cf-field/input/action-button-test.js
> fix: remove flakey test

- package.json
- packages/core/package.json
- pnpm-lock.yaml
Without this, the `dependencyStatisfies` embroider macro won't work -
see https://github.com/embroider-build/embroider/issues/1169#issuecomment-1081943925
for details.
> fix: add optional peer dep on ember data

- packages/form/translations/fr.yaml
Changes "optional" in French to "optionnelle". That is, according to one of our French speaking clients, the correct translation.
> fix(translations): change "optional" to "optionnelle"

- packages/form-builder/addon/components/cfb-form-editor/cfb-advanced-settings.hbs
- packages/form-builder/addon/components/cfb-form-editor/cfb-advanced-settings.js
Especially when jumping between questions and working on JEXLs it's inconvenient that the "advanced settings" always need to be reshown.
> feat(form-builder): save the preference for "show advanced" settings in localStorage

- packages/form-builder/addon/components/cfb-form-editor/question-list/item.hbs
- packages/form-builder/addon/components/cfb-form-editor/question-list/item.js
This is another small quality of life improvement.
When editing a question:
When removing a question:
(it doesn't make a difference when adding a question because you can't add a question that is already in the form)
> feat(form-builder): highlight the slug of the question that is currently being edited in bold

- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
Currently, the form-builder shows "this question is being used in -1 forms" when creating a new question.
> fix(form-builder): don't show the question usage when creating a new question

- packages/form/addon/components/cf-field/input/table.js
If a table is being closed (doesn't matter whether via close or save button) the table question must be validated as the data inside the row document might have changed.
> fix(form): validate table question every time the modal is closed

- packages/form/addon/gql/fragments/case-form-and-workflow.graphql
- packages/form/addon/gql/queries/document-answers.graphql
- packages/form/addon/lib/document.js
- packages/form/addon/lib/field.js
- packages/form/tests/integration/components/document-validity-test.js
- packages/form/tests/unit/lib/data.js
- packages/form/tests/unit/lib/document-test.js
- packages/form/tests/unit/lib/field-test.js
This is convenient when you'd like to write a JEXL expression in a task form attached to some work item, that depends on the case's main documents' form.
Related backend MRs: 
- https://github.com/projectcaluma/caluma/pull/2204
- https://github.com/projectcaluma/caluma/pull/2205
> feat(form): add case infos to jexl context

- packages/form/addon/components/cf-field/input/textarea.hbs
- packages/form/tests/integration/components/cf-field/input/text-test.js
- packages/form/tests/integration/components/cf-field/input/textarea-test.js
When `field.refreshAnswer` is called a new answer value gets set.
But for HTML textareas the value between the tags `<textarea>foo</textarea>` only acts as a default. To update the actual value one would have to update the `value` attribute through javascript something like `element.value = "bar"`.
This does not happend currently, the rerendering does not happend for `<textarea>` after `refreshAnswer` but for normal `<input>` it works.
Integration test of this always passes, no matter if its plain html textarea or ember textarea. Actually doing it over the UI in an app, causes the new value not be displayed.
Let me know if there is an better fix for this than using the ember component.
> fix(form): use ember textarea component to correctly rerender values

- packages/form/addon/components/cf-field/input/table.hbs
- packages/form/addon/components/cf-field/input/table.js
- packages/form/translations/de.yaml
- packages/form/translations/en.yaml
- packages/form/translations/fr.yaml
changes text and icon to not be edit when disabled.
stops triggering validation when disabled.
> fix(table): improve table disabled

- packages/-ember-caluma/package.json
- packages/analytics/package.json
- packages/distribution/package.json
- packages/form-builder/package.json
- pnpm-lock.yaml
BREAKING CHANGE: `@projectcaluma/ember-analytics`, `@projectcaluma/distribution` and `@projectcaluma/ember-form-builder` now require the usage of `ember-engines` v0.11.0. If you are using components or helpers of one of those engines in your code, you'll need to add re-exports in your host application to allow this. However, this is strongly discouraged.
> feat(deps): update ember-engines

- packages/-ember-caluma/package.json
- pnpm-lock.yaml
Pin ember-cli-addon-docs until a new release (7.0.3) is made.
> fix: pin ember-cli-addon-docs to specific commit until new release

- packages/analytics/addon/components/ca-report-preview.hbs
- packages/analytics/addon/components/ca-report-preview.js
- packages/analytics/app/styles/@projectcaluma/ember-analytics.scss
Display new lines in analytics table. As it is not openable like a normal caluma table.
Without the change the newline information would be entirely lost on the analytics user.
New look
> fix(analytics): display new lines in table

- packages/form/addon/components/cf-field-value.hbs
- packages/form/tests/integration/components/cf-field-value-test.js
- packages/form/tests/integration/components/cf-field/input/table-test.js
This change is supposed to fix the value of a calculated_float field not showing in a table row.
The value does not show up currently because the answer for calculated_float fields is not written, just evaluated (see `get calculatedValue()` in `packages/form/addon/lib/field.js`)
no dependencies
> fix(form): showing of field value in case of calculated questions

- packages/form-builder/addon/validators/jexl.js
adds the length jexl transform to the validators for frontend form validation
> fix: add length transform to validators

- packages/form-builder/addon/components/cfb-form-editor/question/default.js
Multiple Choice and Choice question default answer was not selectable because `lib/question` expected the `raw` format while default answer was passing a list of changesets for the options
Fixes #2851
> fix(form-builder): default answer not selectable for choice questions

- packages/form-builder/addon/components/cfb-form-editor/question.hbs
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/addon/gql/mutations/save-float-question.graphql
- packages/form-builder/addon/gql/queries/form-editor-question.graphql
- packages/form-builder/addon/validations/question.js
- packages/form-builder/tests/integration/components/cfb-form-editor/question-test.js
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form-builder/translations/fr.yaml
- packages/form-builder/translations/it.yaml
- packages/form/addon/components/cf-field/input/float.hbs
- packages/form/addon/components/cf-field/input/float.js
- packages/form/addon/gql/fragments/field.graphql
- packages/form/tests/integration/components/cf-field/input/float-test.js
- packages/testing/addon/mirage-graphql/schema.graphql
Add ability to configure the HTML attribute `step` on `type="number"` FloatQuestion fields.
Depends on https://github.com/projectcaluma/caluma/pull/2362
> feat(float): add step configuration

- packages/form-builder/addon/components/cfb-form-editor/question-option.hbs
- packages/form-builder/addon/components/cfb-form-editor/question-option.js
- packages/form-builder/addon/components/cfb-form-editor/question.js
- packages/form-builder/addon/components/cfb-form-editor/question/default.hbs
- packages/form-builder/addon/components/cfb-form-editor/question/default.js
- packages/form-builder/addon/components/cfb-form-editor/question/options.hbs
- packages/form-builder/addon/components/cfb-form-editor/question/options.js
- packages/form-builder/addon/gql/mutations/save-option.graphql
- packages/form-builder/addon/gql/queries/form-editor-question.graphql
- packages/form-builder/translations/de.yaml
- packages/form-builder/translations/en.yaml
- packages/form-builder/translations/fr.yaml
- packages/form-builder/translations/it.yaml
- packages/form/addon/gql/fragments/field.graphql
- packages/form/addon/lib/field.js
- packages/form/addon/lib/question.js
- packages/form/tests/unit/lib/field-test.js
- packages/testing/addon-mirage-support/factories/option.js
- packages/testing/addon/mirage-graphql/schema.graphql
Adds JEXLs to options for choice and multiple choice questions.
If an option has been selected which becomes invisible due to it's JEXL it behaves like an option that isn't available anymore.
Form builder:
Fixes # (issue)
Depends on ~~https://github.com/projectcaluma/caluma/pull/2269~~ (merged)
> feat: enable JEXLs for options in choice and multiple choice questions

- packages/form/addon/components/cf-field.js
Remove logic to bypass timeout during a field save. 
Multiple quick consecutive saves can happen with
every question type, and the debouncing timeout
makes errors due to multiple answer creation
requests less likely.
> fix(form): remove bypassTimeout from field save

- packages/form-builder/addon/components/cfb-form-editor/question-list/item.js
This drops the usage of actual JEXL evaluation in the question list of the form builder in favour of static analysis of the expression (true or false). The problem with the evaluation was, that if an expression only uses context (e.g. `info.form`) it didn't throw and error but evaluated to false. This caused such questions to be marked as always visible when in truth, they'd be conditionally hidden.
> fix(form-builder): fix hidden and required indicators in form-builder

- packages/form/addon/gql/fragments/field.graphql
`DynamicChoiceQuestion` and `DynamicMultipleChoiceQuestion` support querying the `hintText` property. This should resolve the issue where no hint text is displayed for dynamic questions (via the `CfField` component) despite a hint text being set via FormBuilder.
> fix(gql): fetch hintText for Dynamic{,Multiple}ChoiceQuestions as well

- packages/form/addon/lib/document.js
- packages/form/addon/lib/field.js
This PR proposes 2 fixes in JEXL evaluation. 
Currently, the JEXL evaluation is completely skipped when all depending fields are hidden or empty, this should be changed to only skip when they are hidden.
**Take the following example:**
`field-a` is visible, but has no value
`field-b` has a hidden JEXL expression `"field-a"|answer("no") == "yes"`
So, field-b is a field we only want to hide when field-a is set to "yes". But currently the JEXL evaluation completely skipped and ignored (so just hiding field-b), because field-a has no value, and the default value passed through the answer transform is also ignored. 
So, without this fix it is not possible to show/hide field-b based on the value of field-a, until you actually save a value in field-a. (You would expect this answer transform in …
> JEXL evaluation fixes

- packages/form/addon/lib/field.js
Revert the JEXL trigger condition to skip on empty dependending question answers in the minor release changes.
In https://github.com/projectcaluma/ember-caluma/pull/2935 we created a bugfix to trigger JEXL evaluations only when depending questions are hidden, not when they are empty. This is currently not in sync with the backend logic and it should be reverted for now in the minor release changes.
We will still plan to re-introduce the bugfix in a major upgrade on a later stage, in sync with the backend logic.
> chore(jexl): revert JEXL evaluation condition
